# aha
# Autogenerated from man page /usr/share/man/man1/aha.1.gz
# using Deroffing man parser
complete -c aha -l help -s h -s '?' --description 'A help like this.'
complete -c aha -l black -s b --description 'Black Background and white "standard color".'
complete -c aha -l pink -s p --description 'Pink Background.'
complete -c aha -l iso -s i --description 'Uses ISO 8859-X instead of utf-8.  X must be 1. 16.'
complete -c aha -l title -s t --description 'Gives the html output the title \\"X\\" instead o… [See Man Page]'
complete -c aha -l line-fix -s l --description 'Uses a fix for inputs using control sequences t… [See Man Page]'
complete -c aha -l word-wrap -s w --description 'Wrap long lines in the html file.'
complete -c aha -l no-header -s n --description 'Don\'t include header into generated HTML, usefu… [See Man Page]'

