# apachetop
# Autogenerated from man page /usr/share/man/man1/apachetop.1.gz
# using Deroffing man parser
complete -c apachetop -s f --description 'Select which file to watch.'
complete -c apachetop -s H -s T --description 'These options are mutually exclusive.'
complete -c apachetop -s q --description 'Instructs ApacheTop to keep the querystrings, not remove them.'
complete -c apachetop -s l --description 'Instructs ApacheTop to lowercase all URLs, thus… [See Man Page]'
complete -c apachetop -s s --description 'Instructs ApacheTop to only keep the first <seg… [See Man Page]'
complete -c apachetop -s p --description 'Instructs ApacheTop to keep the protocol (http:… [See Man Page]'
complete -c apachetop -s r --description 'Set default refresh delay, in seconds.  EXAMPLES.'

