# appletviewer
# Autogenerated from man page /usr/share/man/man1/appletviewer.1.gz
# using Deroffing man parser
complete -c appletviewer -o debug --description 'br Starts the Applet Viewer in the Java debugge… [See Man Page]'
complete -c appletviewer -o encoding --description 'br Specifies the input HTML file encoding name.'
complete -c appletviewer -o Jjavaoption --description '.'

