# ccguess
# Autogenerated from man page /usr/share/man/man1/ccguess.1.gz
# using Deroffing man parser
complete -c ccguess -s h -l help --description 'Help.  Print usage information and exit.'
complete -c ccguess -s L -l license --description 'Print license info and exit.'
complete -c ccguess -s V -l version --description 'Print version info and exit.'
complete -c ccguess -s K -l key --description 'Specify the approximate key on the command line… [See Man Page]'
complete -c ccguess -s d -l depth --description 'Search keys that contain up to n changes.  The default is 5.'
complete -c ccguess -s c -l continue --description 'Keep trying more keys even after the first match is found.'
complete -c ccguess -s t -l chartable --description 'Specify the list of characters to try for repla… [See Man Page]'
complete -c ccguess -s n -l non-printable --description 'Allow non-printable characters in keys.'

