# chkrootkit
# Autogenerated from man page /usr/share/man/man1/chkrootkit.1.gz
# using Deroffing man parser
complete -c chkrootkit -s h --description 'Print a short help message and exit.'
complete -c chkrootkit -s V --description 'Print version information and exit.'
complete -c chkrootkit -s l --description 'Print available tests.'
complete -c chkrootkit -s d --description 'Enter debug mode.'
complete -c chkrootkit -s x --description 'Enter expert mode.'
complete -c chkrootkit -s e --description 'Exclude known false positive files/dirs, quoted… [See Man Page]'
complete -c chkrootkit -s q --description 'Enter quiet mode.'
complete -c chkrootkit -s r --description 'Use   dir as the root directory.'
complete -c chkrootkit -s p --description 'Specify the path for the external commands used by chkrootkit.'
complete -c chkrootkit -s n --description 'skip NFS mounted dirs.'

