# cloud-publish-image
# Autogenerated from man page /usr/share/man/man1/cloud-publish-image.1.gz
# using Deroffing man parser
complete -c cloud-publish-image -s l -l add-launch --description 'user_id can be "all", or "none".'
complete -c cloud-publish-image -l dry-run --description 'only report what would be done.'
complete -c cloud-publish-image -l allow-existing --description 'if a image is already registered simply report … [See Man Page]'
complete -c cloud-publish-image -s o -l output --description 'write registered id and manifest to file.'
complete -c cloud-publish-image -l rename --description 'publish to bucket/<publish_path>, default: buck… [See Man Page]'
complete -c cloud-publish-image -s t -l type --description 'type is one of kernel/ramdisk/image/auto.'
complete -c cloud-publish-image -l save-downloaded --description 'save the download image to directory \'d\' (appli… [See Man Page]'
complete -c cloud-publish-image -s v -l verbose --description 'increase verbosity.'
complete -c cloud-publish-image -l name --description 'register image with given name.  basename(publish_path).'

