# cloud-publish-tarball
# Autogenerated from man page /usr/share/man/man1/cloud-publish-tarball.1.gz
# using Deroffing man parser
complete -c cloud-publish-tarball -s k -l kernel --description 'Use previously registered kernel with id \'k\' sp… [See Man Page]'
complete -c cloud-publish-tarball -s K -l kernel-file --description 'Bundle, upload, use file \'f\' as kernel.'
complete -c cloud-publish-tarball -s q -l quiet --description 'Be quiet, only output produced image ids.'
complete -c cloud-publish-tarball -s r -l ramdisk --description 'Use previously registered ramdisk with id \'r\' s… [See Man Page]'
complete -c cloud-publish-tarball -s R -l ramdisk-file --description 'Bundle, upload, use file \'f\' as ramdisk.'
complete -c cloud-publish-tarball -l rename-image --description 'rename the image file before publishing (publis… [See Man Page]'
complete -c cloud-publish-tarball -l rename-kernel --description 'rename the kernel file before publishing (publi… [See Man Page]'
complete -c cloud-publish-tarball -l rename-ramdisk --description 'rename the ramdisk file before publishing (publ… [See Man Page]'
complete -c cloud-publish-tarball -l save-downloaded --description 'save the download image to directory \'d\' (appli… [See Man Page]'

