# dnstop
# Autogenerated from man page /usr/share/man/man8/dnstop.8.gz
# using Darwin man parser
complete -c dnstop -s 4 --description 'count only messages with IPv4 addresses.'
complete -c dnstop -s 6 --description 'count only messages with IPv6 addresses.'
complete -c dnstop -s Q --description 'count only DNS query messages.'
complete -c dnstop -s R --description 'count only DNS reply messages.'
complete -c dnstop -s a --description 'anonymize addresses.'
complete -c dnstop -s b --description 'BPF filter expression br (default: udp port 53).'
complete -c dnstop -s i --description 'ignore select addresses.'
complete -c dnstop -s p --description 'Do not put the interface into promiscuous mode.'
complete -c dnstop -s r --description 'Redraw interval (seconds).'
complete -c dnstop -s l --description 'keep counts on names up to level domain name levels.'
complete -c dnstop -s f --description 'input filter name Pp The "unknown-tlds" filter … [See Man Page]'
complete -c dnstop -s n --description 'Only count messages within the domain name.'
complete -c dnstop -s P --description 'Print "progress" messages on stderr when in non… [See Man Page]'
complete -c dnstop -s B --description 'Use buckets hash table buckets.'
complete -c dnstop -s X --description 'Do not tabulate the sources + query name counters.'

