# euare-accountlistpolicies
# Autogenerated from man page /usr/share/man/man1/euare-accountlistpolicies.1.gz
# using Deroffing man parser
complete -c euare-accountlistpolicies -s a -l account-name --description 'account owning the policies to list.'
complete -c euare-accountlistpolicies -s p -l policy-name --description 'display a specific policy.'
complete -c euare-accountlistpolicies -s v -l verbose --description 'display the contents of the resulting policies … [See Man Page]'
complete -c euare-accountlistpolicies -l pretty-print --description 'when printing the contents of policies, reforma… [See Man Page]'
complete -c euare-accountlistpolicies -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountlistpolicies -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountlistpolicies -l debug --description 'show debugging output.'
complete -c euare-accountlistpolicies -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountlistpolicies -l version --description 'show the program\'s version and exit.'
complete -c euare-accountlistpolicies -s I -l access-key-id --description '.'
complete -c euare-accountlistpolicies -s S -l secret-key --description '.'
complete -c euare-accountlistpolicies -s h -l help --description 'show this help message and exit.'

