# euare-groupadduser
# Autogenerated from man page /usr/share/man/man1/euare-groupadduser.1.gz
# using Deroffing man parser
complete -c euare-groupadduser -s g -l group-name --description 'group to add the user to.'
complete -c euare-groupadduser -s u -l user-name --description 'user to add.'
complete -c euare-groupadduser -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-groupadduser -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-groupadduser -s U -l url --description 'identity service endpoint URL .'
complete -c euare-groupadduser -l debug --description 'show debugging output.'
complete -c euare-groupadduser -l debugger --description 'launch interactive debugger on error.'
complete -c euare-groupadduser -l version --description 'show the program\'s version and exit.'
complete -c euare-groupadduser -s I -l access-key-id --description '.'
complete -c euare-groupadduser -s S -l secret-key --description '.'
complete -c euare-groupadduser -s h -l help --description 'show this help message and exit.'

