# euare-useruploadpolicy
# Autogenerated from man page /usr/share/man/man1/euare-useruploadpolicy.1.gz
# using Deroffing man parser
complete -c euare-useruploadpolicy -s u -l user-name --description 'user to attach the policy to (required).'
complete -c euare-useruploadpolicy -s p -l policy-name --description 'name of the policy (required).'
complete -c euare-useruploadpolicy -s o -l policy-content --description 'the policy to attach.'
complete -c euare-useruploadpolicy -s f -l policy-document --description 'file containing the policy to attach.'
complete -c euare-useruploadpolicy -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-useruploadpolicy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-useruploadpolicy -s U -l url --description 'identity service endpoint URL .'
complete -c euare-useruploadpolicy -l debug --description 'show debugging output.'
complete -c euare-useruploadpolicy -l debugger --description 'launch interactive debugger on error.'
complete -c euare-useruploadpolicy -l version --description 'show the program\'s version and exit.'
complete -c euare-useruploadpolicy -s I -l access-key-id --description '.'
complete -c euare-useruploadpolicy -s S -l secret-key --description '.'
complete -c euare-useruploadpolicy -s h -l help --description 'show this help message and exit.'

