# euare-groupremoveuser
# Autogenerated from man page /usr/share/man/man1/euare-groupremoveuser.1.gz
# using Deroffing man parser
complete -c euare-groupremoveuser -s u -l user-name --description 'user to remove from the group (required).'
complete -c euare-groupremoveuser -s g -l group-name --description 'group to remove the user from (required).'
complete -c euare-groupremoveuser -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-groupremoveuser -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-groupremoveuser -s U -l url --description 'identity service endpoint URL .'
complete -c euare-groupremoveuser -l debug --description 'show debugging output.'
complete -c euare-groupremoveuser -l debugger --description 'launch interactive debugger on error.'
complete -c euare-groupremoveuser -l version --description 'show the program\'s version and exit.'
complete -c euare-groupremoveuser -s I -l access-key-id --description '.'
complete -c euare-groupremoveuser -s S -l secret-key --description '.'
complete -c euare-groupremoveuser -s h -l help --description 'show this help message and exit.'

