# euare-servercertupload
# Autogenerated from man page /usr/share/man/man1/euare-servercertupload.1.gz
# using Deroffing man parser
complete -c euare-servercertupload -s s -l server-certificate-name --description 'name to give the new server certificate (required).'
complete -c euare-servercertupload -s c -l certificate-body --description 'PEM-encoded certificate.'
complete -c euare-servercertupload -l certificate-file --description 'file containing the PEM-encoded certificate.'
complete -c euare-servercertupload -l private-key --description 'PEM-encoded private key.'
complete -c euare-servercertupload -l private-key-file --description 'file containing the PEM-encoded private key.'
complete -c euare-servercertupload -l certificate-chain --description 'PEM-encoded certificate chain.'
complete -c euare-servercertupload -l certificate-chain-file --description 'file containing the PEM-encoded certificate chain.'
complete -c euare-servercertupload -s p -l path --description 'path for the new server certificate (default: "/").'
complete -c euare-servercertupload -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-servercertupload -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-servercertupload -s U -l url --description 'identity service endpoint URL .'
complete -c euare-servercertupload -l debug --description 'show debugging output.'
complete -c euare-servercertupload -l debugger --description 'launch interactive debugger on error.'
complete -c euare-servercertupload -l version --description 'show the program\'s version and exit.'
complete -c euare-servercertupload -s I -l access-key-id --description '.'
complete -c euare-servercertupload -s S -l secret-key --description '.'
complete -c euare-servercertupload -s h -l help --description 'show this help message and exit.'

