# euare-usermod
# Autogenerated from man page /usr/share/man/man1/euare-usermod.1.gz
# using Deroffing man parser
complete -c euare-usermod -s u -l user-name --description 'name of the user to update.'
complete -c euare-usermod -s n -l new-user-name --description 'new name for the user.'
complete -c euare-usermod -s p -l new-path --description 'new path for the user.'
complete -c euare-usermod -l enabled --description '[Eucalyptus only] \'true\' to enable the user, or… [See Man Page]'
complete -c euare-usermod -l reg-status --description '[Eucalyptus only] new registration status.'
complete -c euare-usermod -l pwd-expires --description '[Eucalyptus only] New password expiration date,… [See Man Page]'
complete -c euare-usermod -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usermod -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usermod -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usermod -l debug --description 'show debugging output.'
complete -c euare-usermod -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usermod -l version --description 'show the program\'s version and exit.'
complete -c euare-usermod -s I -l access-key-id --description '.'
complete -c euare-usermod -s S -l secret-key --description '.'
complete -c euare-usermod -s h -l help --description 'show this help message and exit.'

