# euare-usermodloginprofile
# Autogenerated from man page /usr/share/man/man1/euare-usermodloginprofile.1.gz
# using Deroffing man parser
complete -c euare-usermodloginprofile -s u -l user-name --description 'name of the user to change a password for (required).'
complete -c euare-usermodloginprofile -s p -l password --description 'the new password.'
complete -c euare-usermodloginprofile -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usermodloginprofile -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usermodloginprofile -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usermodloginprofile -l debug --description 'show debugging output.'
complete -c euare-usermodloginprofile -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usermodloginprofile -l version --description 'show the program\'s version and exit.'
complete -c euare-usermodloginprofile -s I -l access-key-id --description '.'
complete -c euare-usermodloginprofile -s S -l secret-key --description '.'
complete -c euare-usermodloginprofile -s h -l help --description 'show this help message and exit.'

