# euare-accountaliascreate
# Autogenerated from man page /usr/share/man/man1/euare-accountaliascreate.1.gz
# using Deroffing man parser
complete -c euare-accountaliascreate -s a -l account-alias --description 'name of the alias to create (required).'
complete -c euare-accountaliascreate -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-accountaliascreate -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountaliascreate -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountaliascreate -l debug --description 'show debugging output.'
complete -c euare-accountaliascreate -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountaliascreate -l version --description 'show the program\'s version and exit.'
complete -c euare-accountaliascreate -s I -l access-key-id --description '.'
complete -c euare-accountaliascreate -s S -l secret-key --description '.'
complete -c euare-accountaliascreate -s h -l help --description 'show this help message and exit.'

