# euare-useraddpolicy
# Autogenerated from man page /usr/share/man/man1/euare-useraddpolicy.1.gz
# using Deroffing man parser
complete -c euare-useraddpolicy -s u -l user-name --description 'user to attach the policy to (required).'
complete -c euare-useraddpolicy -s p -l policy-name --description 'name of the new policy (required).'
complete -c euare-useraddpolicy -s e -l effect --description 'whether the new policy should Allow or Deny (required).'
complete -c euare-useraddpolicy -s a -l action --description 'action the policy should apply to (required).'
complete -c euare-useraddpolicy -s r -l resource --description 'resource the policy should apply to (required).'
complete -c euare-useraddpolicy -s o -l output --description 'display the newly-created policy.'
complete -c euare-useraddpolicy -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-useraddpolicy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-useraddpolicy -s U -l url --description 'identity service endpoint URL .'
complete -c euare-useraddpolicy -l debug --description 'show debugging output.'
complete -c euare-useraddpolicy -l debugger --description 'launch interactive debugger on error.'
complete -c euare-useraddpolicy -l version --description 'show the program\'s version and exit.'
complete -c euare-useraddpolicy -s I -l access-key-id --description '.'
complete -c euare-useraddpolicy -s S -l secret-key --description '.'
complete -c euare-useraddpolicy -s h -l help --description 'show this help message and exit.'

