# euare-groupgetpolicy
# Autogenerated from man page /usr/share/man/man1/euare-groupgetpolicy.1.gz
# using Deroffing man parser
complete -c euare-groupgetpolicy -s g -l group-name --description 'group the policy is attached to (required).'
complete -c euare-groupgetpolicy -s p -l policy-name --description 'name of the policy to show (required).'
complete -c euare-groupgetpolicy -l pretty-print --description 'reformat the policy for easier reading.'
complete -c euare-groupgetpolicy -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-groupgetpolicy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-groupgetpolicy -s U -l url --description 'identity service endpoint URL .'
complete -c euare-groupgetpolicy -l debug --description 'show debugging output.'
complete -c euare-groupgetpolicy -l debugger --description 'launch interactive debugger on error.'
complete -c euare-groupgetpolicy -l version --description 'show the program\'s version and exit.'
complete -c euare-groupgetpolicy -s I -l access-key-id --description '.'
complete -c euare-groupgetpolicy -s S -l secret-key --description '.'
complete -c euare-groupgetpolicy -s h -l help --description 'show this help message and exit.'

