# euare-accountaliasdelete
# Autogenerated from man page /usr/share/man/man1/euare-accountaliasdelete.1.gz
# using Deroffing man parser
complete -c euare-accountaliasdelete -s a -l account-alias --description 'name of the alias to delete (required).'
complete -c euare-accountaliasdelete -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-accountaliasdelete -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountaliasdelete -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountaliasdelete -l debug --description 'show debugging output.'
complete -c euare-accountaliasdelete -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountaliasdelete -l version --description 'show the program\'s version and exit.'
complete -c euare-accountaliasdelete -s I -l access-key-id --description '.'
complete -c euare-accountaliasdelete -s S -l secret-key --description '.'
complete -c euare-accountaliasdelete -s h -l help --description 'show this help message and exit.'

