# euare-accountgetsummary
# Autogenerated from man page /usr/share/man/man1/euare-accountgetsummary.1.gz
# using Deroffing man parser
complete -c euare-accountgetsummary -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountgetsummary -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountgetsummary -l debug --description 'show debugging output.'
complete -c euare-accountgetsummary -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountgetsummary -l version --description 'show the program\'s version and exit.'
complete -c euare-accountgetsummary -s I -l access-key-id --description '.'
complete -c euare-accountgetsummary -s S -l secret-key --description '.'
complete -c euare-accountgetsummary -s h -l help --description 'show this help message and exit.'

