# euare-userdel
# Autogenerated from man page /usr/share/man/man1/euare-userdel.1.gz
# using Deroffing man parser
complete -c euare-userdel -s u -l user-name --description 'name of the user to delete (required).'
complete -c euare-userdel -s r -l recursive --description 'remove all IAM resources associated with the user first.'
complete -c euare-userdel -s p -l pretend --description 'list the resources that would be deleted instea… [See Man Page]'
complete -c euare-userdel -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userdel -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userdel -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userdel -l debug --description 'show debugging output.'
complete -c euare-userdel -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userdel -l version --description 'show the program\'s version and exit.'
complete -c euare-userdel -s I -l access-key-id --description '.'
complete -c euare-userdel -s S -l secret-key --description '.'
complete -c euare-userdel -s h -l help --description 'show this help message and exit.'

