# euare-grouplistpolicies
# Autogenerated from man page /usr/share/man/man1/euare-grouplistpolicies.1.gz
# using Deroffing man parser
complete -c euare-grouplistpolicies -s g -l group-name --description 'group owning the policies to list.'
complete -c euare-grouplistpolicies -s p -l policy-name --description 'display a specific policy.'
complete -c euare-grouplistpolicies -s v -l verbose --description 'display the contents of the resulting policies … [See Man Page]'
complete -c euare-grouplistpolicies -l pretty-print --description 'when printing the contents of policies, reforma… [See Man Page]'
complete -c euare-grouplistpolicies -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-grouplistpolicies -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-grouplistpolicies -s U -l url --description 'identity service endpoint URL .'
complete -c euare-grouplistpolicies -l debug --description 'show debugging output.'
complete -c euare-grouplistpolicies -l debugger --description 'launch interactive debugger on error.'
complete -c euare-grouplistpolicies -l version --description 'show the program\'s version and exit.'
complete -c euare-grouplistpolicies -s I -l access-key-id --description '.'
complete -c euare-grouplistpolicies -s S -l secret-key --description '.'
complete -c euare-grouplistpolicies -s h -l help --description 'show this help message and exit.'

