# euare-accountdel
# Autogenerated from man page /usr/share/man/man1/euare-accountdel.1.gz
# using Deroffing man parser
complete -c euare-accountdel -s a -l account-name --description 'name of the account to delete (required).'
complete -c euare-accountdel -s r -l recursive --description 'delete all users, groups, and policies associat… [See Man Page]'
complete -c euare-accountdel -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountdel -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountdel -l debug --description 'show debugging output.'
complete -c euare-accountdel -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountdel -l version --description 'show the program\'s version and exit.'
complete -c euare-accountdel -s I -l access-key-id --description '.'
complete -c euare-accountdel -s S -l secret-key --description '.'
complete -c euare-accountdel -s h -l help --description 'show this help message and exit.'

