# euare-userlistpolicies
# Autogenerated from man page /usr/share/man/man1/euare-userlistpolicies.1.gz
# using Deroffing man parser
complete -c euare-userlistpolicies -s u -l user-name --description 'user owning the policies to list.'
complete -c euare-userlistpolicies -s p -l policy-name --description 'display a specific policy.'
complete -c euare-userlistpolicies -s v -l verbose --description 'display the contents of the resulting policies … [See Man Page]'
complete -c euare-userlistpolicies -l pretty-print --description 'when printing the contents of policies, reforma… [See Man Page]'
complete -c euare-userlistpolicies -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userlistpolicies -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userlistpolicies -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userlistpolicies -l debug --description 'show debugging output.'
complete -c euare-userlistpolicies -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userlistpolicies -l version --description 'show the program\'s version and exit.'
complete -c euare-userlistpolicies -s I -l access-key-id --description '.'
complete -c euare-userlistpolicies -s S -l secret-key --description '.'
complete -c euare-userlistpolicies -s h -l help --description 'show this help message and exit.'

