# euare-usergetloginprofile
# Autogenerated from man page /usr/share/man/man1/euare-usergetloginprofile.1.gz
# using Deroffing man parser
complete -c euare-usergetloginprofile -s u -l user-name --description 'user whose password to verify (required).'
complete -c euare-usergetloginprofile -l verbose --description 'print extra info about the user\'s password.'
complete -c euare-usergetloginprofile -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usergetloginprofile -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usergetloginprofile -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usergetloginprofile -l debug --description 'show debugging output.'
complete -c euare-usergetloginprofile -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usergetloginprofile -l version --description 'show the program\'s version and exit.'
complete -c euare-usergetloginprofile -s I -l access-key-id --description '.'
complete -c euare-usergetloginprofile -s S -l secret-key --description '.'
complete -c euare-usergetloginprofile -s h -l help --description 'show this help message and exit.'

