# euare-getldapsyncstatus
# Autogenerated from man page /usr/share/man/man1/euare-getldapsyncstatus.1.gz
# using Deroffing man parser
complete -c euare-getldapsyncstatus -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euare-getldapsyncstatus -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-getldapsyncstatus -s U -l url --description 'identity service endpoint URL .'
complete -c euare-getldapsyncstatus -l debug --description 'show debugging output.'
complete -c euare-getldapsyncstatus -l debugger --description 'launch interactive debugger on error.'
complete -c euare-getldapsyncstatus -l version --description 'show the program\'s version and exit.'
complete -c euare-getldapsyncstatus -s I -l access-key-id --description '.'
complete -c euare-getldapsyncstatus -s S -l secret-key --description '.'
complete -c euare-getldapsyncstatus -s h -l help --description 'show this help message and exit.'

