# euare-userresyncmfadevice
# Autogenerated from man page /usr/share/man/man1/euare-userresyncmfadevice.1.gz
# using Deroffing man parser
complete -c euare-userresyncmfadevice -s u -l user-name --description 'user to re-synchronize the MFA device for (required).'
complete -c euare-userresyncmfadevice -s s -l serial-number --description 'serial number of the MFA device (required).'
complete -c euare-userresyncmfadevice -o c1 --description 'an authentication code emitted by the MFA device (required).'
complete -c euare-userresyncmfadevice -o c2 --description 'a subsequent authentication code emitted by the… [See Man Page]'
complete -c euare-userresyncmfadevice -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userresyncmfadevice -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userresyncmfadevice -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userresyncmfadevice -l debug --description 'show debugging output.'
complete -c euare-userresyncmfadevice -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userresyncmfadevice -l version --description 'show the program\'s version and exit.'
complete -c euare-userresyncmfadevice -s I -l access-key-id --description '.'
complete -c euare-userresyncmfadevice -s S -l secret-key --description '.'
complete -c euare-userresyncmfadevice -s h -l help --description 'show this help message and exit.'

