# euare-userlistgroups
# Autogenerated from man page /usr/share/man/man1/euare-userlistgroups.1.gz
# using Deroffing man parser
complete -c euare-userlistgroups -s u -l user-name --description 'user to list membership for (required).'
complete -c euare-userlistgroups -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userlistgroups -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userlistgroups -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userlistgroups -l debug --description 'show debugging output.'
complete -c euare-userlistgroups -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userlistgroups -l version --description 'show the program\'s version and exit.'
complete -c euare-userlistgroups -s I -l access-key-id --description '.'
complete -c euare-userlistgroups -s S -l secret-key --description '.'
complete -c euare-userlistgroups -s h -l help --description 'show this help message and exit.'

