# euare-accountlist
# Autogenerated from man page /usr/share/man/man1/euare-accountlist.1.gz
# using Deroffing man parser
complete -c euare-accountlist -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euare-accountlist -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountlist -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountlist -l debug --description 'show debugging output.'
complete -c euare-accountlist -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountlist -l version --description 'show the program\'s version and exit.'
complete -c euare-accountlist -s I -l access-key-id --description '.'
complete -c euare-accountlist -s S -l secret-key --description '.'
complete -c euare-accountlist -s h -l help --description 'show this help message and exit.'

