# euare-usermodcert
# Autogenerated from man page /usr/share/man/man1/euare-usermodcert.1.gz
# using Deroffing man parser
complete -c euare-usermodcert -s u -l user-name --description 'user owning the signing certificate to update (… [See Man Page]'
complete -c euare-usermodcert -s c -l certificate-id --description 'ID of the signing certificate to update.'
complete -c euare-usermodcert -s s -l status --description 'status to assign to the certificate.'
complete -c euare-usermodcert -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usermodcert -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usermodcert -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usermodcert -l debug --description 'show debugging output.'
complete -c euare-usermodcert -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usermodcert -l version --description 'show the program\'s version and exit.'
complete -c euare-usermodcert -s I -l access-key-id --description '.'
complete -c euare-usermodcert -s S -l secret-key --description '.'
complete -c euare-usermodcert -s h -l help --description 'show this help message and exit.'

