# euare-servercertmod
# Autogenerated from man page /usr/share/man/man1/euare-servercertmod.1.gz
# using Deroffing man parser
complete -c euare-servercertmod -s s -l server-certificate-name --description 'name of the server certificate to update.'
complete -c euare-servercertmod -s n -l new-server-certificate-name --description 'new name for the server certificate.'
complete -c euare-servercertmod -s p -l new-path --description 'new path for the server certificate.'
complete -c euare-servercertmod -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-servercertmod -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-servercertmod -s U -l url --description 'identity service endpoint URL .'
complete -c euare-servercertmod -l debug --description 'show debugging output.'
complete -c euare-servercertmod -l debugger --description 'launch interactive debugger on error.'
complete -c euare-servercertmod -l version --description 'show the program\'s version and exit.'
complete -c euare-servercertmod -s I -l access-key-id --description '.'
complete -c euare-servercertmod -s S -l secret-key --description '.'
complete -c euare-servercertmod -s h -l help --description 'show this help message and exit.'

