# euare-usercreate
# Autogenerated from man page /usr/share/man/man1/euare-usercreate.1.gz
# using Deroffing man parser
complete -c euare-usercreate -s u -l user-name --description 'name of the new user.'
complete -c euare-usercreate -s p -l path --description 'path for the new user (default: "/").'
complete -c euare-usercreate -s g -l group-name --description 'add the new user to a group.'
complete -c euare-usercreate -s k -l create-accesskey --description 'create an access key for the new user and print… [See Man Page]'
complete -c euare-usercreate -s v -l verbose --description 'print the new user\'s ARN and GUID.'
complete -c euare-usercreate -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usercreate -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usercreate -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usercreate -l debug --description 'show debugging output.'
complete -c euare-usercreate -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usercreate -l version --description 'show the program\'s version and exit.'
complete -c euare-usercreate -s I -l access-key-id --description '.'
complete -c euare-usercreate -s S -l secret-key --description '.'
complete -c euare-usercreate -s h -l help --description 'show this help message and exit.'

