# euare-usercreatecert
# Autogenerated from man page /usr/share/man/man1/euare-usercreatecert.1.gz
# using Deroffing man parser
complete -c euare-usercreatecert -s u -l user-name --description 'user to create the signing certificate for (required).'
complete -c euare-usercreatecert -l out --description 'file to write the certificate to (default: stdout).'
complete -c euare-usercreatecert -l keyout --description 'file to write the private key to (default: stdout).'
complete -c euare-usercreatecert -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usercreatecert -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usercreatecert -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usercreatecert -l debug --description 'show debugging output.'
complete -c euare-usercreatecert -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usercreatecert -l version --description 'show the program\'s version and exit.'
complete -c euare-usercreatecert -s I -l access-key-id --description '.'
complete -c euare-usercreatecert -s S -l secret-key --description '.'
complete -c euare-usercreatecert -s h -l help --description 'show this help message and exit.'

