# euare-userlistmfadevices
# Autogenerated from man page /usr/share/man/man1/euare-userlistmfadevices.1.gz
# using Deroffing man parser
complete -c euare-userlistmfadevices -s u -l user-name --description 'user to list MFA devices for (default: current user).'
complete -c euare-userlistmfadevices -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userlistmfadevices -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userlistmfadevices -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userlistmfadevices -l debug --description 'show debugging output.'
complete -c euare-userlistmfadevices -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userlistmfadevices -l version --description 'show the program\'s version and exit.'
complete -c euare-userlistmfadevices -s I -l access-key-id --description '.'
complete -c euare-userlistmfadevices -s S -l secret-key --description '.'
complete -c euare-userlistmfadevices -s h -l help --description 'show this help message and exit.'

