# euare-groupuploadpolicy
# Autogenerated from man page /usr/share/man/man1/euare-groupuploadpolicy.1.gz
# using Deroffing man parser
complete -c euare-groupuploadpolicy -s g -l group-name --description 'group to attach the policy to (required).'
complete -c euare-groupuploadpolicy -s p -l policy-name --description 'name of the policy (required).'
complete -c euare-groupuploadpolicy -s o -l policy-content --description 'the policy to attach.'
complete -c euare-groupuploadpolicy -s f -l policy-document --description 'file containing the policy to attach.'
complete -c euare-groupuploadpolicy -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-groupuploadpolicy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-groupuploadpolicy -s U -l url --description 'identity service endpoint URL .'
complete -c euare-groupuploadpolicy -l debug --description 'show debugging output.'
complete -c euare-groupuploadpolicy -l debugger --description 'launch interactive debugger on error.'
complete -c euare-groupuploadpolicy -l version --description 'show the program\'s version and exit.'
complete -c euare-groupuploadpolicy -s I -l access-key-id --description '.'
complete -c euare-groupuploadpolicy -s S -l secret-key --description '.'
complete -c euare-groupuploadpolicy -s h -l help --description 'show this help message and exit.'

