# euare-usergetattributes
# Autogenerated from man page /usr/share/man/man1/euare-usergetattributes.1.gz
# using Deroffing man parser
complete -c euare-usergetattributes -s u -l user-name --description 'name of the user to show info about (default: current user).'
complete -c euare-usergetattributes -l show-extra --description 'also display additional user info.'
complete -c euare-usergetattributes -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usergetattributes -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usergetattributes -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usergetattributes -l debug --description 'show debugging output.'
complete -c euare-usergetattributes -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usergetattributes -l version --description 'show the program\'s version and exit.'
complete -c euare-usergetattributes -s I -l access-key-id --description '.'
complete -c euare-usergetattributes -s S -l secret-key --description '.'
complete -c euare-usergetattributes -s h -l help --description 'show this help message and exit.'

