# euare-usergetpolicy
# Autogenerated from man page /usr/share/man/man1/euare-usergetpolicy.1.gz
# using Deroffing man parser
complete -c euare-usergetpolicy -s u -l user-name --description 'user the poilcy is attached to (required).'
complete -c euare-usergetpolicy -s p -l policy-name --description 'name of the policy to show (required).'
complete -c euare-usergetpolicy -l pretty-print --description 'reformat the policy for easier reading.'
complete -c euare-usergetpolicy -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usergetpolicy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usergetpolicy -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usergetpolicy -l debug --description 'show debugging output.'
complete -c euare-usergetpolicy -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usergetpolicy -l version --description 'show the program\'s version and exit.'
complete -c euare-usergetpolicy -s I -l access-key-id --description '.'
complete -c euare-usergetpolicy -s S -l secret-key --description '.'
complete -c euare-usergetpolicy -s h -l help --description 'show this help message and exit.'

