# euare-groupmod
# Autogenerated from man page /usr/share/man/man1/euare-groupmod.1.gz
# using Deroffing man parser
complete -c euare-groupmod -s g -l group-name --description 'name of the group to update.'
complete -c euare-groupmod -s n -l new-group-name --description 'new name for the group.'
complete -c euare-groupmod -s p -l new-path --description 'new path for the group.'
complete -c euare-groupmod -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-groupmod -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-groupmod -s U -l url --description 'identity service endpoint URL .'
complete -c euare-groupmod -l debug --description 'show debugging output.'
complete -c euare-groupmod -l debugger --description 'launch interactive debugger on error.'
complete -c euare-groupmod -l version --description 'show the program\'s version and exit.'
complete -c euare-groupmod -s I -l access-key-id --description '.'
complete -c euare-groupmod -s S -l secret-key --description '.'
complete -c euare-groupmod -s h -l help --description 'show this help message and exit.'

