# euare-userupdateinfo
# Autogenerated from man page /usr/share/man/man1/euare-userupdateinfo.1.gz
# using Deroffing man parser
complete -c euare-userupdateinfo -s u -l user-name --description 'user to update (default: current user).'
complete -c euare-userupdateinfo -s k -l info-key --description 'name of the info field to set (required).'
complete -c euare-userupdateinfo -s i -l info-value --description 'value to set the info field to (omit to delete it).'
complete -c euare-userupdateinfo -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userupdateinfo -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userupdateinfo -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userupdateinfo -l debug --description 'show debugging output.'
complete -c euare-userupdateinfo -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userupdateinfo -l version --description 'show the program\'s version and exit.'
complete -c euare-userupdateinfo -s I -l access-key-id --description '.'
complete -c euare-userupdateinfo -s S -l secret-key --description '.'
complete -c euare-userupdateinfo -s h -l help --description 'show this help message and exit.'

