# euare-useraddloginprofile
# Autogenerated from man page /usr/share/man/man1/euare-useraddloginprofile.1.gz
# using Deroffing man parser
complete -c euare-useraddloginprofile -s u -l user-name --description 'name of the user to create a password for (required).'
complete -c euare-useraddloginprofile -s p -l password --description 'the new password.'
complete -c euare-useraddloginprofile -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-useraddloginprofile -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-useraddloginprofile -s U -l url --description 'identity service endpoint URL .'
complete -c euare-useraddloginprofile -l debug --description 'show debugging output.'
complete -c euare-useraddloginprofile -l debugger --description 'launch interactive debugger on error.'
complete -c euare-useraddloginprofile -l version --description 'show the program\'s version and exit.'
complete -c euare-useraddloginprofile -s I -l access-key-id --description '.'
complete -c euare-useraddloginprofile -s S -l secret-key --description '.'
complete -c euare-useraddloginprofile -s h -l help --description 'show this help message and exit.'

