# euare-groupdel
# Autogenerated from man page /usr/share/man/man1/euare-groupdel.1.gz
# using Deroffing man parser
complete -c euare-groupdel -s g -l group-name --description 'name of the group to delete (required).'
complete -c euare-groupdel -s r -l recursive --description 'remove all user memberships and policies associ… [See Man Page]'
complete -c euare-groupdel -s p -l pretend --description 'list the user memberships and policies that wou… [See Man Page]'
complete -c euare-groupdel -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-groupdel -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-groupdel -s U -l url --description 'identity service endpoint URL .'
complete -c euare-groupdel -l debug --description 'show debugging output.'
complete -c euare-groupdel -l debugger --description 'launch interactive debugger on error.'
complete -c euare-groupdel -l version --description 'show the program\'s version and exit.'
complete -c euare-groupdel -s I -l access-key-id --description '.'
complete -c euare-groupdel -s S -l secret-key --description '.'
complete -c euare-groupdel -s h -l help --description 'show this help message and exit.'

