# euare-userlistkeys
# Autogenerated from man page /usr/share/man/man1/euare-userlistkeys.1.gz
# using Deroffing man parser
complete -c euare-userlistkeys -s u -l user-name --description 'user to list keys for (default: current user).'
complete -c euare-userlistkeys -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userlistkeys -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userlistkeys -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userlistkeys -l debug --description 'show debugging output.'
complete -c euare-userlistkeys -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userlistkeys -l version --description 'show the program\'s version and exit.'
complete -c euare-userlistkeys -s I -l access-key-id --description '.'
complete -c euare-userlistkeys -s S -l secret-key --description '.'
complete -c euare-userlistkeys -s h -l help --description 'show this help message and exit.'

