# euare-usermodkey
# Autogenerated from man page /usr/share/man/man1/euare-usermodkey.1.gz
# using Deroffing man parser
complete -c euare-usermodkey -s u -l user-name --description 'user owning the access key to update (default: current user).'
complete -c euare-usermodkey -s k -l user-key-id --description 'ID of the access key to update (required).'
complete -c euare-usermodkey -s s -l status --description 'status to assign to the access key.'
complete -c euare-usermodkey -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usermodkey -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usermodkey -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usermodkey -l debug --description 'show debugging output.'
complete -c euare-usermodkey -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usermodkey -l version --description 'show the program\'s version and exit.'
complete -c euare-usermodkey -s I -l access-key-id --description '.'
complete -c euare-usermodkey -s S -l secret-key --description '.'
complete -c euare-usermodkey -s h -l help --description 'show this help message and exit.'

