# euare-useraddcert
# Autogenerated from man page /usr/share/man/man1/euare-useraddcert.1.gz
# using Deroffing man parser
complete -c euare-useraddcert -s c -l certificate-body --description 'contents of the new certificate.'
complete -c euare-useraddcert -s f -l certificate-file --description 'file containing the new certificate.'
complete -c euare-useraddcert -s u -l user-name --description 'user the signing certificate is for (default: current user).'
complete -c euare-useraddcert -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-useraddcert -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-useraddcert -s U -l url --description 'identity service endpoint URL .'
complete -c euare-useraddcert -l debug --description 'show debugging output.'
complete -c euare-useraddcert -l debugger --description 'launch interactive debugger on error.'
complete -c euare-useraddcert -l version --description 'show the program\'s version and exit.'
complete -c euare-useraddcert -s I -l access-key-id --description '.'
complete -c euare-useraddcert -s S -l secret-key --description '.'
complete -c euare-useraddcert -s h -l help --description 'show this help message and exit.'

