# euare-accountuploadpolicy
# Autogenerated from man page /usr/share/man/man1/euare-accountuploadpolicy.1.gz
# using Deroffing man parser
complete -c euare-accountuploadpolicy -s a -l account-name --description 'account to attach the policy to (required).'
complete -c euare-accountuploadpolicy -s p -l policy-name --description 'name of the policy (required).'
complete -c euare-accountuploadpolicy -s o -l policy-content --description 'the policy to attach.'
complete -c euare-accountuploadpolicy -s f -l policy-document --description 'file containing the policy to attach.'
complete -c euare-accountuploadpolicy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountuploadpolicy -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountuploadpolicy -l debug --description 'show debugging output.'
complete -c euare-accountuploadpolicy -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountuploadpolicy -l version --description 'show the program\'s version and exit.'
complete -c euare-accountuploadpolicy -s I -l access-key-id --description '.'
complete -c euare-accountuploadpolicy -s S -l secret-key --description '.'
complete -c euare-accountuploadpolicy -s h -l help --description 'show this help message and exit.'

