# euare-servercertdel
# Autogenerated from man page /usr/share/man/man1/euare-servercertdel.1.gz
# using Deroffing man parser
complete -c euare-servercertdel -s s -l server-certificate-name --description 'name of the server certificate to delete (required).'
complete -c euare-servercertdel -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-servercertdel -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-servercertdel -s U -l url --description 'identity service endpoint URL .'
complete -c euare-servercertdel -l debug --description 'show debugging output.'
complete -c euare-servercertdel -l debugger --description 'launch interactive debugger on error.'
complete -c euare-servercertdel -l version --description 'show the program\'s version and exit.'
complete -c euare-servercertdel -s I -l access-key-id --description '.'
complete -c euare-servercertdel -s S -l secret-key --description '.'
complete -c euare-servercertdel -s h -l help --description 'show this help message and exit.'

