# euare-grouplistbypath
# Autogenerated from man page /usr/share/man/man1/euare-grouplistbypath.1.gz
# using Deroffing man parser
complete -c euare-grouplistbypath -s p -l path-prefix --description 'restrict results to groups whose paths begin wi… [See Man Page]'
complete -c euare-grouplistbypath -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-grouplistbypath -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-grouplistbypath -s U -l url --description 'identity service endpoint URL .'
complete -c euare-grouplistbypath -l debug --description 'show debugging output.'
complete -c euare-grouplistbypath -l debugger --description 'launch interactive debugger on error.'
complete -c euare-grouplistbypath -l version --description 'show the program\'s version and exit.'
complete -c euare-grouplistbypath -s I -l access-key-id --description '.'
complete -c euare-grouplistbypath -s S -l secret-key --description '.'
complete -c euare-grouplistbypath -s h -l help --description 'show this help message and exit.'

