# euare-accountcreate
# Autogenerated from man page /usr/share/man/man1/euare-accountcreate.1.gz
# using Deroffing man parser
complete -c euare-accountcreate -s a -l account-name --description 'name of the account to create (required).'
complete -c euare-accountcreate -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euare-accountcreate -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountcreate -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountcreate -l debug --description 'show debugging output.'
complete -c euare-accountcreate -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountcreate -l version --description 'show the program\'s version and exit.'
complete -c euare-accountcreate -s I -l access-key-id --description '.'
complete -c euare-accountcreate -s S -l secret-key --description '.'
complete -c euare-accountcreate -s h -l help --description 'show this help message and exit.'

