# euare-useraddkey
# Autogenerated from man page /usr/share/man/man1/euare-useraddkey.1.gz
# using Deroffing man parser
complete -c euare-useraddkey -s u -l user-name --description 'user the new key will belong to (default: calling user).'
complete -c euare-useraddkey -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-useraddkey -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-useraddkey -s U -l url --description 'identity service endpoint URL .'
complete -c euare-useraddkey -l debug --description 'show debugging output.'
complete -c euare-useraddkey -l debugger --description 'launch interactive debugger on error.'
complete -c euare-useraddkey -l version --description 'show the program\'s version and exit.'
complete -c euare-useraddkey -s I -l access-key-id --description '.'
complete -c euare-useraddkey -s S -l secret-key --description '.'
complete -c euare-useraddkey -s h -l help --description 'show this help message and exit.'

