# euare-groupcreate
# Autogenerated from man page /usr/share/man/man1/euare-groupcreate.1.gz
# using Deroffing man parser
complete -c euare-groupcreate -s g -l group-name --description 'name of the new group (required).'
complete -c euare-groupcreate -s p -l path --description 'path for the new group (default: "/").'
complete -c euare-groupcreate -s v -l verbose --description 'print the new group\'s ARN and GUID.'
complete -c euare-groupcreate -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-groupcreate -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-groupcreate -s U -l url --description 'identity service endpoint URL .'
complete -c euare-groupcreate -l debug --description 'show debugging output.'
complete -c euare-groupcreate -l debugger --description 'launch interactive debugger on error.'
complete -c euare-groupcreate -l version --description 'show the program\'s version and exit.'
complete -c euare-groupcreate -s I -l access-key-id --description '.'
complete -c euare-groupcreate -s S -l secret-key --description '.'
complete -c euare-groupcreate -s h -l help --description 'show this help message and exit.'

