# euare-userlistbypath
# Autogenerated from man page /usr/share/man/man1/euare-userlistbypath.1.gz
# using Deroffing man parser
complete -c euare-userlistbypath -s p -l path-prefix --description 'limit results to users who begin with a given path.'
complete -c euare-userlistbypath -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userlistbypath -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userlistbypath -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userlistbypath -l debug --description 'show debugging output.'
complete -c euare-userlistbypath -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userlistbypath -l version --description 'show the program\'s version and exit.'
complete -c euare-userlistbypath -s I -l access-key-id --description '.'
complete -c euare-userlistbypath -s S -l secret-key --description '.'
complete -c euare-userlistbypath -s h -l help --description 'show this help message and exit.'

