# euare-usergetinfo
# Autogenerated from man page /usr/share/man/man1/euare-usergetinfo.1.gz
# using Deroffing man parser
complete -c euare-usergetinfo -s u -l user-name --description 'name of the user to display info for (default: current user).'
complete -c euare-usergetinfo -s k -l info-key --description 'name of the piece of user info to show.'
complete -c euare-usergetinfo -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-usergetinfo -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euare-usergetinfo -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-usergetinfo -s U -l url --description 'identity service endpoint URL .'
complete -c euare-usergetinfo -l debug --description 'show debugging output.'
complete -c euare-usergetinfo -l debugger --description 'launch interactive debugger on error.'
complete -c euare-usergetinfo -l version --description 'show the program\'s version and exit.'
complete -c euare-usergetinfo -s I -l access-key-id --description '.'
complete -c euare-usergetinfo -s S -l secret-key --description '.'
complete -c euare-usergetinfo -s h -l help --description 'show this help message and exit.'

