# euare-userdelkey
# Autogenerated from man page /usr/share/man/man1/euare-userdelkey.1.gz
# using Deroffing man parser
complete -c euare-userdelkey -s u -l user-name --description 'user whose key to delete (required).'
complete -c euare-userdelkey -s k -l user-key-id --description 'ID of the access key to delete (required).'
complete -c euare-userdelkey -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userdelkey -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userdelkey -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userdelkey -l debug --description 'show debugging output.'
complete -c euare-userdelkey -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userdelkey -l version --description 'show the program\'s version and exit.'
complete -c euare-userdelkey -s I -l access-key-id --description '.'
complete -c euare-userdelkey -s S -l secret-key --description '.'
complete -c euare-userdelkey -s h -l help --description 'show this help message and exit.'

