# euare-userlistcerts
# Autogenerated from man page /usr/share/man/man1/euare-userlistcerts.1.gz
# using Deroffing man parser
complete -c euare-userlistcerts -s u -l user-name --description 'user to list certificates for (default: current user).'
complete -c euare-userlistcerts -s v -l verbose --description 'also show certificates\' contents.'
complete -c euare-userlistcerts -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userlistcerts -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userlistcerts -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userlistcerts -l debug --description 'show debugging output.'
complete -c euare-userlistcerts -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userlistcerts -l version --description 'show the program\'s version and exit.'
complete -c euare-userlistcerts -s I -l access-key-id --description '.'
complete -c euare-userlistcerts -s S -l secret-key --description '.'
complete -c euare-userlistcerts -s h -l help --description 'show this help message and exit.'

