# euare-userdelcert
# Autogenerated from man page /usr/share/man/man1/euare-userdelcert.1.gz
# using Deroffing man parser
complete -c euare-userdelcert -s u -l user-name --description 'user the signing certificate belongs to (required).'
complete -c euare-userdelcert -s c -l certificate-id --description 'ID of the signing certificate to delete (required).'
complete -c euare-userdelcert -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userdelcert -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userdelcert -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userdelcert -l debug --description 'show debugging output.'
complete -c euare-userdelcert -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userdelcert -l version --description 'show the program\'s version and exit.'
complete -c euare-userdelcert -s I -l access-key-id --description '.'
complete -c euare-userdelcert -s S -l secret-key --description '.'
complete -c euare-userdelcert -s h -l help --description 'show this help message and exit.'

