# euare-accountgetpolicy
# Autogenerated from man page /usr/share/man/man1/euare-accountgetpolicy.1.gz
# using Deroffing man parser
complete -c euare-accountgetpolicy -s a -l account-name --description 'account the policy is attached to (required).'
complete -c euare-accountgetpolicy -s p -l policy-name --description 'name of the policy to show (required).'
complete -c euare-accountgetpolicy -l pretty-print --description 'reformat the policy for easier reading.'
complete -c euare-accountgetpolicy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountgetpolicy -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountgetpolicy -l debug --description 'show debugging output.'
complete -c euare-accountgetpolicy -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountgetpolicy -l version --description 'show the program\'s version and exit.'
complete -c euare-accountgetpolicy -s I -l access-key-id --description '.'
complete -c euare-accountgetpolicy -s S -l secret-key --description '.'
complete -c euare-accountgetpolicy -s h -l help --description 'show this help message and exit.'

