# euare-grouplistusers
# Autogenerated from man page /usr/share/man/man1/euare-grouplistusers.1.gz
# using Deroffing man parser
complete -c euare-grouplistusers -s g -l group-name --description 'name of the group to show info about.'
complete -c euare-grouplistusers -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-grouplistusers -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-grouplistusers -s U -l url --description 'identity service endpoint URL .'
complete -c euare-grouplistusers -l debug --description 'show debugging output.'
complete -c euare-grouplistusers -l debugger --description 'launch interactive debugger on error.'
complete -c euare-grouplistusers -l version --description 'show the program\'s version and exit.'
complete -c euare-grouplistusers -s I -l access-key-id --description '.'
complete -c euare-grouplistusers -s S -l secret-key --description '.'
complete -c euare-grouplistusers -s h -l help --description 'show this help message and exit.'

