# euare-userdeactivatemfadevice
# Autogenerated from man page /usr/share/man/man1/euare-userdeactivatemfadevice.1.gz
# using Deroffing man parser
complete -c euare-userdeactivatemfadevice -s u -l user-name --description 'user whose MFA device to deactivate (required).'
complete -c euare-userdeactivatemfadevice -s s -l serial-number --description 'serial number of the MFA device to deactivate (required).'
complete -c euare-userdeactivatemfadevice -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userdeactivatemfadevice -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userdeactivatemfadevice -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userdeactivatemfadevice -l debug --description 'show debugging output.'
complete -c euare-userdeactivatemfadevice -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userdeactivatemfadevice -l version --description 'show the program\'s version and exit.'
complete -c euare-userdeactivatemfadevice -s I -l access-key-id --description '.'
complete -c euare-userdeactivatemfadevice -s S -l secret-key --description '.'
complete -c euare-userdeactivatemfadevice -s h -l help --description 'show this help message and exit.'

