# euare-accountaliaslist
# Autogenerated from man page /usr/share/man/man1/euare-accountaliaslist.1.gz
# using Deroffing man parser
complete -c euare-accountaliaslist -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-accountaliaslist -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountaliaslist -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountaliaslist -l debug --description 'show debugging output.'
complete -c euare-accountaliaslist -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountaliaslist -l version --description 'show the program\'s version and exit.'
complete -c euare-accountaliaslist -s I -l access-key-id --description '.'
complete -c euare-accountaliaslist -s S -l secret-key --description '.'
complete -c euare-accountaliaslist -s h -l help --description 'show this help message and exit.'

