# euare-userenablemfadevice
# Autogenerated from man page /usr/share/man/man1/euare-userenablemfadevice.1.gz
# using Deroffing man parser
complete -c euare-userenablemfadevice -s u -l user-name --description 'user to enable the MFA device for (required).'
complete -c euare-userenablemfadevice -s s -l serial-number --description 'serial number of the MFA device to activate (required).'
complete -c euare-userenablemfadevice -o c1 --description 'an authentication code emitted by the MFA device (required).'
complete -c euare-userenablemfadevice -o c2 --description 'a subsequent authentication code emitted by the… [See Man Page]'
complete -c euare-userenablemfadevice -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userenablemfadevice -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userenablemfadevice -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userenablemfadevice -l debug --description 'show debugging output.'
complete -c euare-userenablemfadevice -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userenablemfadevice -l version --description 'show the program\'s version and exit.'
complete -c euare-userenablemfadevice -s I -l access-key-id --description '.'
complete -c euare-userenablemfadevice -s S -l secret-key --description '.'
complete -c euare-userenablemfadevice -s h -l help --description 'show this help message and exit.'

