# euare-accountdelpolicy
# Autogenerated from man page /usr/share/man/man1/euare-accountdelpolicy.1.gz
# using Deroffing man parser
complete -c euare-accountdelpolicy -s a -l account-name --description 'account the policy is attached to (required).'
complete -c euare-accountdelpolicy -s p -l policy-name --description 'name of the policy to delete (required).'
complete -c euare-accountdelpolicy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-accountdelpolicy -s U -l url --description 'identity service endpoint URL .'
complete -c euare-accountdelpolicy -l debug --description 'show debugging output.'
complete -c euare-accountdelpolicy -l debugger --description 'launch interactive debugger on error.'
complete -c euare-accountdelpolicy -l version --description 'show the program\'s version and exit.'
complete -c euare-accountdelpolicy -s I -l access-key-id --description '.'
complete -c euare-accountdelpolicy -s S -l secret-key --description '.'
complete -c euare-accountdelpolicy -s h -l help --description 'show this help message and exit.'

