# euare-userdelpolicy
# Autogenerated from man page /usr/share/man/man1/euare-userdelpolicy.1.gz
# using Deroffing man parser
complete -c euare-userdelpolicy -s u -l user-name --description 'user the policy is attached to (required).'
complete -c euare-userdelpolicy -s p -l policy-name --description 'name of the policy to delete (required).'
complete -c euare-userdelpolicy -l as-account --description '[Eucalyptus cloud admin only] run this command … [See Man Page]'
complete -c euare-userdelpolicy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euare-userdelpolicy -s U -l url --description 'identity service endpoint URL .'
complete -c euare-userdelpolicy -l debug --description 'show debugging output.'
complete -c euare-userdelpolicy -l debugger --description 'launch interactive debugger on error.'
complete -c euare-userdelpolicy -l version --description 'show the program\'s version and exit.'
complete -c euare-userdelpolicy -s I -l access-key-id --description '.'
complete -c euare-userdelpolicy -s S -l secret-key --description '.'
complete -c euare-userdelpolicy -s h -l help --description 'show this help message and exit.'

