# euca-modify-instance-type
# Autogenerated from man page /usr/share/man/man1/euca-modify-instance-type.1.gz
# using Deroffing man parser
complete -c euca-modify-instance-type -s c -l cpus --description 'number of virtual CPUs to allocate to each instance.'
complete -c euca-modify-instance-type -s d -l disk --description 'amount of instance storage to allow each instance.'
complete -c euca-modify-instance-type -s m -l memory --description 'amount of RAM to allocate to each instance.'
complete -c euca-modify-instance-type -l reset --description 'reset the instance type to its default configuration.'
complete -c euca-modify-instance-type -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-modify-instance-type -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-modify-instance-type -s U -l url --description 'compute service endpoint URL .'
complete -c euca-modify-instance-type -l debug --description 'show debugging output.'
complete -c euca-modify-instance-type -l debugger --description 'launch interactive debugger on error.'
complete -c euca-modify-instance-type -l version --description 'show the program\'s version and exit.'
complete -c euca-modify-instance-type -s I -l access-key-id --description '.'
complete -c euca-modify-instance-type -s S -l secret-key --description '.'
complete -c euca-modify-instance-type -s h -l help --description 'show this help message and exit.'

