# euca-associate-address
# Autogenerated from man page /usr/share/man/man1/euca-associate-address.1.gz
# using Deroffing man parser
complete -c euca-associate-address -s i -l instance-id --description 'ID of the instance to associate the address with.'
complete -c euca-associate-address -s n -l network-interface --description '[VPC only] network interface to associate the address with.'
complete -c euca-associate-address -s a -l allocation-id --description '[VPC only] VPC allocation ID (required).'
complete -c euca-associate-address -s p -l private-ip-address --description '[VPC only] the private address to associate wit… [See Man Page]'
complete -c euca-associate-address -l allow-reassociation --description '[VPC only] allow the address to be associated e… [See Man Page]'
complete -c euca-associate-address -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-associate-address -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-associate-address -s U -l url --description 'compute service endpoint URL .'
complete -c euca-associate-address -l debug --description 'show debugging output.'
complete -c euca-associate-address -l debugger --description 'launch interactive debugger on error.'
complete -c euca-associate-address -l version --description 'show the program\'s version and exit.'
complete -c euca-associate-address -s I -l access-key-id --description '.'
complete -c euca-associate-address -s S -l secret-key --description '.'
complete -c euca-associate-address -s h -l help --description 'show this help message and exit.'

