# euca-cancel-bundle-task
# Autogenerated from man page /usr/share/man/man1/euca-cancel-bundle-task.1.gz
# using Deroffing man parser
complete -c euca-cancel-bundle-task -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-cancel-bundle-task -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-cancel-bundle-task -s U -l url --description 'compute service endpoint URL .'
complete -c euca-cancel-bundle-task -l debug --description 'show debugging output.'
complete -c euca-cancel-bundle-task -l debugger --description 'launch interactive debugger on error.'
complete -c euca-cancel-bundle-task -l version --description 'show the program\'s version and exit.'
complete -c euca-cancel-bundle-task -s I -l access-key-id --description '.'
complete -c euca-cancel-bundle-task -s S -l secret-key --description '.'
complete -c euca-cancel-bundle-task -s h -l help --description 'show this help message and exit.'

