# euca-modify-snapshot-attribute
# Autogenerated from man page /usr/share/man/man1/euca-modify-snapshot-attribute.1.gz
# using Deroffing man parser
complete -c euca-modify-snapshot-attribute -s c -l create-volume-permission --description 'grant/revoke volume creation permission with -a/-r.'
complete -c euca-modify-snapshot-attribute -s a -l add --description 'account to grant permission, or "all" for all accounts.'
complete -c euca-modify-snapshot-attribute -s r -l remove --description 'account to remove permission from, or "all" for all accounts.'
complete -c euca-modify-snapshot-attribute -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-modify-snapshot-attribute -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-modify-snapshot-attribute -s U -l url --description 'compute service endpoint URL .'
complete -c euca-modify-snapshot-attribute -l debug --description 'show debugging output.'
complete -c euca-modify-snapshot-attribute -l debugger --description 'launch interactive debugger on error.'
complete -c euca-modify-snapshot-attribute -l version --description 'show the program\'s version and exit.'
complete -c euca-modify-snapshot-attribute -s I -l access-key-id --description '.'
complete -c euca-modify-snapshot-attribute -s S -l secret-key --description '.'
complete -c euca-modify-snapshot-attribute -s h -l help --description 'show this help message and exit.'

