# euca-get-console-output
# Autogenerated from man page /usr/share/man/man1/euca-get-console-output.1.gz
# using Deroffing man parser
complete -c euca-get-console-output -s r -l raw-console-output --description 'display raw output without escaping control characters.'
complete -c euca-get-console-output -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-get-console-output -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-get-console-output -s U -l url --description 'compute service endpoint URL .'
complete -c euca-get-console-output -l debug --description 'show debugging output.'
complete -c euca-get-console-output -l debugger --description 'launch interactive debugger on error.'
complete -c euca-get-console-output -l version --description 'show the program\'s version and exit.'
complete -c euca-get-console-output -s I -l access-key-id --description '.'
complete -c euca-get-console-output -s S -l secret-key --description '.'
complete -c euca-get-console-output -s h -l help --description 'show this help message and exit ENVIRONMENT VARIABLES.'

