# euca-authorize
# Autogenerated from man page /usr/share/man/man1/euca-authorize.1.gz
# using Deroffing man parser
complete -c euca-authorize -l egress --description '[VPC only] manage an egress rule, which control… [See Man Page]'
complete -c euca-authorize -s P -l protocol --description 'protocol to affect (default: tcp).'
complete -c euca-authorize -s p -l port-range --description 'range of ports (specified as "from-to") or a si… [See Man Page]'
complete -c euca-authorize -s t -l icmp-type-code --description 'ICMP type and code (specified as "type:code") (… [See Man Page]'
complete -c euca-authorize -s s -l cidr --description 'IP range (default: 0. 0. 0. 0/0).'
complete -c euca-authorize -s o --description '[Non-VPC only] name of a security group with wh… [See Man Page]'
complete -c euca-authorize -s u --description 'ID of the account that owns the security group … [See Man Page]'
complete -c euca-authorize -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-authorize -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-authorize -s U -l url --description 'compute service endpoint URL .'
complete -c euca-authorize -l debug --description 'show debugging output.'
complete -c euca-authorize -l debugger --description 'launch interactive debugger on error.'
complete -c euca-authorize -l version --description 'show the program\'s version and exit.'
complete -c euca-authorize -s I -l access-key-id --description '.'
complete -c euca-authorize -s S -l secret-key --description '.'
complete -c euca-authorize -s h -l help --description 'show this help message and exit.'

