# euca-create-keypair
# Autogenerated from man page /usr/share/man/man1/euca-create-keypair.1.gz
# using Deroffing man parser
complete -c euca-create-keypair -s f -l filename --description 'file name to save the private key to.'
complete -c euca-create-keypair -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-create-keypair -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-create-keypair -s U -l url --description 'compute service endpoint URL .'
complete -c euca-create-keypair -l debug --description 'show debugging output.'
complete -c euca-create-keypair -l debugger --description 'launch interactive debugger on error.'
complete -c euca-create-keypair -l version --description 'show the program\'s version and exit.'
complete -c euca-create-keypair -s I -l access-key-id --description '.'
complete -c euca-create-keypair -s S -l secret-key --description '.'
complete -c euca-create-keypair -s h -l help --description 'show this help message and exit.'

