# euca-bundle-upload
# Autogenerated from man page /usr/share/man/man1/euca-bundle-upload.1.gz
# using Deroffing man parser
complete -c euca-bundle-upload -s b -l bucket --description 'bucket to upload the bundle to (required).'
complete -c euca-bundle-upload -s i -l image --description 'file containing the image to bundle (required).'
complete -c euca-bundle-upload -s r -l arch --description 'image architecture (default: x86_64).'
complete -c euca-bundle-upload -s d -l directory --description 'location to place the working directory with temporary files.'
complete -c euca-bundle-upload -l cert --description 'file containing the X.'
complete -c euca-bundle-upload -l privatekey --description 'file containing the private key to use when sig… [See Man Page]'
complete -c euca-bundle-upload -l spoof-key-id --description 'run this command as if signed by a specific access key.'
complete -c euca-bundle-upload -l ec2cert --description 'file containing the cloud\'s X. 509 certificate.'
complete -c euca-bundle-upload -l user --description 'the user\'s account ID.'
complete -c euca-bundle-upload -s c -l upload-policy --description 'Base64-encoded S3 upload policy.'
complete -c euca-bundle-upload -l upload-policy-signature -l policysignature --description 'signature for the upload policy given with --uploadpolicy.'
complete -c euca-bundle-upload -s U -l url --description 'storage service endpoint URL.'
complete -c euca-bundle-upload -l debug --description 'show debugging output.'
complete -c euca-bundle-upload -l debugger --description 'launch interactive debugger on error.'
complete -c euca-bundle-upload -l version --description 'show the program\'s version and exit.'
complete -c euca-bundle-upload -s h -l help --description 'show this help message and exit.'

