# euca-delete-snapshot
# Autogenerated from man page /usr/share/man/man1/euca-delete-snapshot.1.gz
# using Deroffing man parser
complete -c euca-delete-snapshot -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-delete-snapshot -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-delete-snapshot -s U -l url --description 'compute service endpoint URL .'
complete -c euca-delete-snapshot -l debug --description 'show debugging output.'
complete -c euca-delete-snapshot -l debugger --description 'launch interactive debugger on error.'
complete -c euca-delete-snapshot -l version --description 'show the program\'s version and exit.'
complete -c euca-delete-snapshot -s I -l access-key-id --description '.'
complete -c euca-delete-snapshot -s S -l secret-key --description '.'
complete -c euca-delete-snapshot -s h -l help --description 'show this help message and exit.'

