# euca-get-password
# Autogenerated from man page /usr/share/man/man1/euca-get-password.1.gz
# using Deroffing man parser
complete -c euca-get-password -s k -l priv-launch-key --description 'file containing the private key corresponding t… [See Man Page]'
complete -c euca-get-password -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-get-password -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-get-password -s U -l url --description 'compute service endpoint URL .'
complete -c euca-get-password -l debug --description 'show debugging output.'
complete -c euca-get-password -l debugger --description 'launch interactive debugger on error.'
complete -c euca-get-password -l version --description 'show the program\'s version and exit.'
complete -c euca-get-password -s I -l access-key-id --description '.'
complete -c euca-get-password -s S -l secret-key --description '.'
complete -c euca-get-password -s h -l help --description 'show this help message and exit.'

