# euca-describe-snapshots
# Autogenerated from man page /usr/share/man/man1/euca-describe-snapshots.1.gz
# using Deroffing man parser
complete -c euca-describe-snapshots -s a -l all --description 'describe all snapshots.'
complete -c euca-describe-snapshots -s o -l owner --description 'limit results to snapshots owned by specific accounts.'
complete -c euca-describe-snapshots -s r -l restorable-by --description 'limit results to snapahots restorable by specific accounts.'
complete -c euca-describe-snapshots -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-describe-snapshots -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-describe-snapshots -s U -l url --description 'compute service endpoint URL.'
complete -c euca-describe-snapshots -s I -l access-key-id --description '.'
complete -c euca-describe-snapshots -s S -l secret-key --description '.'
complete -c euca-describe-snapshots -l filter --description 'restrict results to those that meet criteria.'
complete -c euca-describe-snapshots -l debug --description 'show debugging output.'
complete -c euca-describe-snapshots -l debugger --description 'launch interactive debugger on error.'
complete -c euca-describe-snapshots -l version --description 'show the program\'s version and exit.'
complete -c euca-describe-snapshots -s h -l help --description 'show this help message and exit allowed filter names:.'

