# euca-create-image
# Autogenerated from man page /usr/share/man/man1/euca-create-image.1.gz
# using Deroffing man parser
complete -c euca-create-image -s n -l name --description 'name for the new image (required).'
complete -c euca-create-image -s d -l description --description 'description for the new image.'
complete -c euca-create-image -l no-reboot --description 'do not shut down the instance before creating the image.'
complete -c euca-create-image -s b -l block-device-mapping --description 'define a block device mapping for the image, in… [See Man Page]'
complete -c euca-create-image -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-create-image -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-create-image -s U -l url --description 'compute service endpoint URL .'
complete -c euca-create-image -l debug --description 'show debugging output.'
complete -c euca-create-image -l debugger --description 'launch interactive debugger on error.'
complete -c euca-create-image -l version --description 'show the program\'s version and exit.'
complete -c euca-create-image -s I -l access-key-id --description '.'
complete -c euca-create-image -s S -l secret-key --description '.'
complete -c euca-create-image -s h -l help --description 'show this help message and exit.'

