# euca-get-password-data
# Autogenerated from man page /usr/share/man/man1/euca-get-password-data.1.gz
# using Deroffing man parser
complete -c euca-get-password-data -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-get-password-data -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-get-password-data -s U -l url --description 'compute service endpoint URL .'
complete -c euca-get-password-data -l debug --description 'show debugging output.'
complete -c euca-get-password-data -l debugger --description 'launch interactive debugger on error.'
complete -c euca-get-password-data -l version --description 'show the program\'s version and exit.'
complete -c euca-get-password-data -s I -l access-key-id --description '.'
complete -c euca-get-password-data -s S -l secret-key --description '.'
complete -c euca-get-password-data -s h -l help --description 'show this help message and exit.'

