# euca-delete-bundle
# Autogenerated from man page /usr/share/man/man1/euca-delete-bundle.1.gz
# using Deroffing man parser
complete -c euca-delete-bundle -s b -l bucket --description 'location of the bundle to delete (required).'
complete -c euca-delete-bundle -s m -l manifest --description 'use a local manifest file to figure out what to delete.'
complete -c euca-delete-bundle -s p -l prefix --description 'delete the bundle that begins with a specific prefix (e. g.'
complete -c euca-delete-bundle -l clear --description 'attempt to delete the bucket as well.'
complete -c euca-delete-bundle -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-delete-bundle -s U -l url --description 'storage service endpoint URL .'
complete -c euca-delete-bundle -l debug --description 'show debugging output.'
complete -c euca-delete-bundle -l debugger --description 'launch interactive debugger on error.'
complete -c euca-delete-bundle -l version --description 'show the program\'s version and exit.'
complete -c euca-delete-bundle -s I -l access-key-id --description '.'
complete -c euca-delete-bundle -s S -l secret-key --description '.'
complete -c euca-delete-bundle -s h -l help --description 'show this help message and exit.'

