# euca-describe-instance-types
# Autogenerated from man page /usr/share/man/man1/euca-describe-instance-types.1.gz
# using Deroffing man parser
complete -c euca-describe-instance-types -l by-zone --description 'show info for each availability zone separately.'
complete -c euca-describe-instance-types -l show-capacity --description 'show info about instance capacity.'
complete -c euca-describe-instance-types -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-describe-instance-types -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-describe-instance-types -s U -l url --description 'compute service endpoint URL .'
complete -c euca-describe-instance-types -l debug --description 'show debugging output.'
complete -c euca-describe-instance-types -l debugger --description 'launch interactive debugger on error.'
complete -c euca-describe-instance-types -l version --description 'show the program\'s version and exit.'
complete -c euca-describe-instance-types -s I -l access-key-id --description '.'
complete -c euca-describe-instance-types -s S -l secret-key --description '.'
complete -c euca-describe-instance-types -s h -l help --description 'show this help message and exit.'

