# euca-detach-volume
# Autogenerated from man page /usr/share/man/man1/euca-detach-volume.1.gz
# using Deroffing man parser
complete -c euca-detach-volume -s i -l instance --description 'instance to detach from.'
complete -c euca-detach-volume -s d -l device --description 'device name.'
complete -c euca-detach-volume -s f -l force --description 'detach without waiting for the instance.  Data may be lost.'
complete -c euca-detach-volume -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-detach-volume -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-detach-volume -s U -l url --description 'compute service endpoint URL .'
complete -c euca-detach-volume -l debug --description 'show debugging output.'
complete -c euca-detach-volume -l debugger --description 'launch interactive debugger on error.'
complete -c euca-detach-volume -l version --description 'show the program\'s version and exit.'
complete -c euca-detach-volume -s I -l access-key-id --description '.'
complete -c euca-detach-volume -s S -l secret-key --description '.'
complete -c euca-detach-volume -s h -l help --description 'show this help message and exit.'

