# euca-bundle-image
# Autogenerated from man page /usr/share/man/man1/euca-bundle-image.1.gz
# using Deroffing man parser
complete -c euca-bundle-image -s i -l image --description 'file containing the image to bundle (required).'
complete -c euca-bundle-image -s p -l prefix --description 'the file name prefix to give the bundle\'s files… [See Man Page]'
complete -c euca-bundle-image -s r -l arch --description 'the image\'s processor architecture (required).'
complete -c euca-bundle-image -s c -l cert --description 'file containing your X. 509 certificate.'
complete -c euca-bundle-image -s k -l privatekey --description 'file containing the private key to sign the bun… [See Man Page]'
complete -c euca-bundle-image -s u -l user --description 'your account ID.'
complete -c euca-bundle-image -l region --description 'use encryption keys and the account ID specifie… [See Man Page]'
complete -c euca-bundle-image -l ec2cert --description 'file containing the cloud\'s X. 509 certificate.'
complete -c euca-bundle-image -l kernel --description 'ID of the kernel image to associate with the machine bundle.'
complete -c euca-bundle-image -l ramdisk --description 'ID of the ramdisk image to associate with the machine bundle.'
complete -c euca-bundle-image -s B -l block-device-mappings --description 'default block device mapping scheme with which … [See Man Page]'
complete -c euca-bundle-image -s d -l destination --description 'location to place the bundle\'s files (default: … [See Man Page]'
complete -c euca-bundle-image -l productcodes --description 'comma-separated list of product codes.'
complete -c euca-bundle-image -l progress --description 'show progress (the default when run interactively).'
complete -c euca-bundle-image -l no-progress --description 'do not show progress (the default when run noninteractively).'
complete -c euca-bundle-image -l debug --description 'show debugging output.'
complete -c euca-bundle-image -l debugger --description 'launch interactive debugger on error.'
complete -c euca-bundle-image -l version --description 'show the program\'s version and exit.'
complete -c euca-bundle-image -s h -l help --description 'show this help message and exit.'

