# euca-confirm-product-instance
# Autogenerated from man page /usr/share/man/man1/euca-confirm-product-instance.1.gz
# using Deroffing man parser
complete -c euca-confirm-product-instance -s i -l instance --description 'ID of the instance to confirm (required).'
complete -c euca-confirm-product-instance -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-confirm-product-instance -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-confirm-product-instance -s U -l url --description 'compute service endpoint URL .'
complete -c euca-confirm-product-instance -l debug --description 'show debugging output.'
complete -c euca-confirm-product-instance -l debugger --description 'launch interactive debugger on error.'
complete -c euca-confirm-product-instance -l version --description 'show the program\'s version and exit.'
complete -c euca-confirm-product-instance -s I -l access-key-id --description '.'
complete -c euca-confirm-product-instance -s S -l secret-key --description '.'
complete -c euca-confirm-product-instance -s h -l help --description 'show this help message and exit.'

