# euca-describe-images
# Autogenerated from man page /usr/share/man/man1/euca-describe-images.1.gz
# using Deroffing man parser
complete -c euca-describe-images -s a -l all --description 'describe all images.'
complete -c euca-describe-images -s o -l owner --description 'describe images owned by the specified owner.'
complete -c euca-describe-images -s x -l executable-by --description 'describe images for which the specified account… [See Man Page]'
complete -c euca-describe-images -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-describe-images -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-describe-images -s U -l url --description 'compute service endpoint URL.'
complete -c euca-describe-images -s I -l access-key-id --description '.'
complete -c euca-describe-images -s S -l secret-key --description '.'
complete -c euca-describe-images -l filter --description 'restrict results to those that meet criteria.'
complete -c euca-describe-images -l debug --description 'show debugging output.'
complete -c euca-describe-images -l debugger --description 'launch interactive debugger on error.'
complete -c euca-describe-images -l version --description 'show the program\'s version and exit.'
complete -c euca-describe-images -s h -l help --description 'show this help message and exit allowed filter names:.'

