# euca-create-volume
# Autogenerated from man page /usr/share/man/man1/euca-create-volume.1.gz
# using Deroffing man parser
complete -c euca-create-volume -s z -l availability-zone -l zone --description 'availability zone in which to create the new volume (required).'
complete -c euca-create-volume -s s -l size --description 'size of the new volume in GiB (required unless … [See Man Page]'
complete -c euca-create-volume -l snapshot --description 'snapshot from which to create the new volume.'
complete -c euca-create-volume -s t -l type --description 'volume type.'
complete -c euca-create-volume -s i -l iops --description 'number of I/O operations per second.'
complete -c euca-create-volume -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-create-volume -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-create-volume -s U -l url --description 'compute service endpoint URL .'
complete -c euca-create-volume -l debug --description 'show debugging output.'
complete -c euca-create-volume -l debugger --description 'launch interactive debugger on error.'
complete -c euca-create-volume -l version --description 'show the program\'s version and exit.'
complete -c euca-create-volume -s I -l access-key-id --description '.'
complete -c euca-create-volume -s S -l secret-key --description '.'
complete -c euca-create-volume -s h -l help --description 'show this help message and exit.'

