# euca-stop-instances
# Autogenerated from man page /usr/share/man/man1/euca-stop-instances.1.gz
# using Deroffing man parser
complete -c euca-stop-instances -s f -l force --description 'immediately stop the instance(s).  Data may be lost.'
complete -c euca-stop-instances -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-stop-instances -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-stop-instances -s U -l url --description 'compute service endpoint URL .'
complete -c euca-stop-instances -l debug --description 'show debugging output.'
complete -c euca-stop-instances -l debugger --description 'launch interactive debugger on error.'
complete -c euca-stop-instances -l version --description 'show the program\'s version and exit.'
complete -c euca-stop-instances -s I -l access-key-id --description '.'
complete -c euca-stop-instances -s S -l secret-key --description '.'
complete -c euca-stop-instances -s h -l help --description 'show this help message and exit.'

