# euca-bundle-instance
# Autogenerated from man page /usr/share/man/man1/euca-bundle-instance.1.gz
# using Deroffing man parser
complete -c euca-bundle-instance -s b -l bucket --description 'bucket in which to store the new machine image (required).'
complete -c euca-bundle-instance -s p -l prefix --description 'beginning of the machine image bundle name (required).'
complete -c euca-bundle-instance -s o -l owner-akid -l user-access-key --description 'bucket owner\'s access key ID (required).'
complete -c euca-bundle-instance -s c -l policy --description 'Base64-encoded upload policy that allows the se… [See Man Page]'
complete -c euca-bundle-instance -s s -l policy-signature --description 'signature of the Base64-encoded upload policy.'
complete -c euca-bundle-instance -s w -l owner-sak -l user-secret-key --description 'bucket owner\'s secret access key, used to sign upload policies.'
complete -c euca-bundle-instance -s x -l expires --description 'generated upload policy expiration time (default: 24).'
complete -c euca-bundle-instance -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-bundle-instance -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-bundle-instance -s U -l url --description 'compute service endpoint URL .'
complete -c euca-bundle-instance -l debug --description 'show debugging output.'
complete -c euca-bundle-instance -l debugger --description 'launch interactive debugger on error.'
complete -c euca-bundle-instance -l version --description 'show the program\'s version and exit.'
complete -c euca-bundle-instance -s I -l access-key-id --description '.'
complete -c euca-bundle-instance -s S -l secret-key --description '.'
complete -c euca-bundle-instance -s h -l help --description 'show this help message and exit.'

