# euca-describe-image-attribute
# Autogenerated from man page /usr/share/man/man1/euca-describe-image-attribute.1.gz
# using Deroffing man parser
complete -c euca-describe-image-attribute -s l -l launch-permission --description 'display launch permissions.'
complete -c euca-describe-image-attribute -s p -l product-codes --description 'list associated product codes.'
complete -c euca-describe-image-attribute -s B -l block-device-mapping --description 'describe block device mappings.'
complete -c euca-describe-image-attribute -l kernel --description 'show associated kernel image ID.'
complete -c euca-describe-image-attribute -l ramdisk --description 'show associated ramdisk image ID.'
complete -c euca-describe-image-attribute -l description --description 'show the image\'s description.'
complete -c euca-describe-image-attribute -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-describe-image-attribute -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-describe-image-attribute -s U -l url --description 'compute service endpoint URL .'
complete -c euca-describe-image-attribute -l debug --description 'show debugging output.'
complete -c euca-describe-image-attribute -l debugger --description 'launch interactive debugger on error.'
complete -c euca-describe-image-attribute -l version --description 'show the program\'s version and exit.'
complete -c euca-describe-image-attribute -s I -l access-key-id --description '.'
complete -c euca-describe-image-attribute -s S -l secret-key --description '.'
complete -c euca-describe-image-attribute -s h -l help --description 'show this help message and exit.'

