# euca-unbundle
# Autogenerated from man page /usr/share/man/man1/euca-unbundle.1.gz
# using Deroffing man parser
complete -c euca-unbundle -s m -l manifest --description 'the bundle\'s manifest file (required).'
complete -c euca-unbundle -s k -l privatekey --description 'file containing the private key to decrypt the bundle with.'
complete -c euca-unbundle -s d -l destination --description 'where to place the unbundled image (default: cu… [See Man Page]'
complete -c euca-unbundle -s s -l source --description 'directory containing the bundled image parts (d… [See Man Page]'
complete -c euca-unbundle -l region --description 'use encryption keys specified for a user and/or… [See Man Page]'
complete -c euca-unbundle -l progress --description 'show progress (the default when run interactively).'
complete -c euca-unbundle -l no-progress --description 'do not show progress (the default when run noninteractively).'
complete -c euca-unbundle -l debug --description 'show debugging output.'
complete -c euca-unbundle -l debugger --description 'launch interactive debugger on error.'
complete -c euca-unbundle -l version --description 'show the program\'s version and exit.'
complete -c euca-unbundle -s h -l help --description 'show this help message and exit.'

