# euca-check-bucket
# Autogenerated from man page /usr/share/man/man1/euca-check-bucket.1.gz
# using Deroffing man parser
complete -c euca-check-bucket -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-check-bucket -s U -l url --description 'storage service endpoint URL.'
complete -c euca-check-bucket -l cert --description 'file containing the X.'
complete -c euca-check-bucket -l privatekey --description 'file containing the private key to sign requests with.'
complete -c euca-check-bucket -l spoof-key-id --description 'run this command as if signed by a specific access key.'
complete -c euca-check-bucket -l debug --description 'show debugging output.'
complete -c euca-check-bucket -l debugger --description 'launch interactive debugger on error.'
complete -c euca-check-bucket -l version --description 'show the program\'s version and exit.'
complete -c euca-check-bucket -s h -l help --description 'show this help message and exit.'

