# euca-register
# Autogenerated from man page /usr/share/man/man1/euca-register.1.gz
# using Deroffing man parser
complete -c euca-register -s n -l name --description 'name of the new image (required).'
complete -c euca-register -s d -l description --description 'description of the new image.'
complete -c euca-register -s a -l architecture --description 'CPU architecture of the new image.'
complete -c euca-register -l kernel --description 'ID of the kernel to associate with the new image.'
complete -c euca-register -l ramdisk --description 'ID of the ramdisk to associate with the new image.'
complete -c euca-register -l root-device-name --description 'root device name (default: /dev/sda1).'
complete -c euca-register -s s -l snapshot --description 'snapshot to use for the root device.'
complete -c euca-register -s b -l block-device-mapping --description 'define a block device mapping for the image, in… [See Man Page]'
complete -c euca-register -l virtualization-type --description '[Privileged] virtualization type for the new image.'
complete -c euca-register -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-register -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-register -s U -l url --description 'compute service endpoint URL .'
complete -c euca-register -l debug --description 'show debugging output.'
complete -c euca-register -l debugger --description 'launch interactive debugger on error.'
complete -c euca-register -l version --description 'show the program\'s version and exit.'
complete -c euca-register -s I -l access-key-id --description '.'
complete -c euca-register -s S -l secret-key --description '.'
complete -c euca-register -s h -l help --description 'show this help message and exit.'

