# euca-upload-bundle
# Autogenerated from man page /usr/share/man/man1/euca-upload-bundle.1.gz
# using Deroffing man parser
complete -c euca-upload-bundle -s b -l bucket --description 'bucket to upload the bundle to (required).'
complete -c euca-upload-bundle -s m -l manifest --description 'manifest for the bundle to upload (required).'
complete -c euca-upload-bundle -l acl --description 'canned ACL policy to apply to the bundle (defau… [See Man Page]'
complete -c euca-upload-bundle -s d -l directory --description 'directory that contains the bundle parts (defau… [See Man Page]'
complete -c euca-upload-bundle -l part --description 'begin uploading with a specific part number (default: 0).'
complete -c euca-upload-bundle -l location --description 'location constraint of the destination bucket (… [See Man Page]'
complete -c euca-upload-bundle -l retry --description 'retry failed uploads up to 5 times.'
complete -c euca-upload-bundle -l skipmanifest --description 'do not upload the manifest.'
complete -c euca-upload-bundle -l progress --description 'show progress (the default when run interactively).'
complete -c euca-upload-bundle -l no-progress --description 'do not show progress (the default when run noninteractively).'
complete -c euca-upload-bundle -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-upload-bundle -s U -l url --description 'storage service endpoint URL .'
complete -c euca-upload-bundle -l debug --description 'show debugging output.'
complete -c euca-upload-bundle -l debugger --description 'launch interactive debugger on error.'
complete -c euca-upload-bundle -l version --description 'show the program\'s version and exit.'
complete -c euca-upload-bundle -s I -l access-key-id --description '.'
complete -c euca-upload-bundle -s S -l secret-key --description '.'
complete -c euca-upload-bundle -s h -l help --description 'show this help message and exit.'

