# euca-create-group
# Autogenerated from man page /usr/share/man/man1/euca-create-group.1.gz
# using Deroffing man parser
complete -c euca-create-group -s d -l description --description 'description of the new group (required).'
complete -c euca-create-group -s c -l vpc --description '[VPC only] ID of the VPC to create the group in.'
complete -c euca-create-group -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-create-group -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-create-group -s U -l url --description 'compute service endpoint URL .'
complete -c euca-create-group -l debug --description 'show debugging output.'
complete -c euca-create-group -l debugger --description 'launch interactive debugger on error.'
complete -c euca-create-group -l version --description 'show the program\'s version and exit.'
complete -c euca-create-group -s I -l access-key-id --description '.'
complete -c euca-create-group -s S -l secret-key --description '.'
complete -c euca-create-group -s h -l help --description 'show this help message and exit.'

