# euca-delete-tags
# Autogenerated from man page /usr/share/man/man1/euca-delete-tags.1.gz
# using Deroffing man parser
complete -c euca-delete-tags -l tag --description 'key and optional value of the tag to delete, se… [See Man Page]'
complete -c euca-delete-tags -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-delete-tags -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-delete-tags -s U -l url --description 'compute service endpoint URL .'
complete -c euca-delete-tags -l debug --description 'show debugging output.'
complete -c euca-delete-tags -l debugger --description 'launch interactive debugger on error.'
complete -c euca-delete-tags -l version --description 'show the program\'s version and exit.'
complete -c euca-delete-tags -s I -l access-key-id --description '.'
complete -c euca-delete-tags -s S -l secret-key --description '.'
complete -c euca-delete-tags -s h -l help --description 'show this help message and exit.'

