# euca-reset-image-attribute
# Autogenerated from man page /usr/share/man/man1/euca-reset-image-attribute.1.gz
# using Deroffing man parser
complete -c euca-reset-image-attribute -s l -l launch-permission --description 'reset launch permissions.'
complete -c euca-reset-image-attribute -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-reset-image-attribute -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-reset-image-attribute -s U -l url --description 'compute service endpoint URL .'
complete -c euca-reset-image-attribute -l debug --description 'show debugging output.'
complete -c euca-reset-image-attribute -l debugger --description 'launch interactive debugger on error.'
complete -c euca-reset-image-attribute -l version --description 'show the program\'s version and exit.'
complete -c euca-reset-image-attribute -s I -l access-key-id --description '.'
complete -c euca-reset-image-attribute -s S -l secret-key --description '.'
complete -c euca-reset-image-attribute -s h -l help --description 'show this help message and exit.'

