# euca-deregister
# Autogenerated from man page /usr/share/man/man1/euca-deregister.1.gz
# using Deroffing man parser
complete -c euca-deregister -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-deregister -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-deregister -s U -l url --description 'compute service endpoint URL.'
complete -c euca-deregister -s I -l access-key-id --description '.'
complete -c euca-deregister -s S -l secret-key --description '.'
complete -c euca-deregister -l debug --description 'show debugging output.'
complete -c euca-deregister -l debugger --description 'launch interactive debugger on error.'
complete -c euca-deregister -l version --description 'show the program\'s version and exit.'
complete -c euca-deregister -s h -l help --description 'show this help message and exit.'

