# euca-modify-image-attribute
# Autogenerated from man page /usr/share/man/man1/euca-modify-image-attribute.1.gz
# using Deroffing man parser
complete -c euca-modify-image-attribute -l description --description 'change the image\'s description.'
complete -c euca-modify-image-attribute -s p -l product-code --description 'product code to add to the given instance-store image.'
complete -c euca-modify-image-attribute -s l -l launch-permission --description 'grant/revoke launch permissions with -a/-r.'
complete -c euca-modify-image-attribute -s a -l add --description 'account to grant launch permission, or "all" for all accounts.'
complete -c euca-modify-image-attribute -s r -l remove --description 'account to remove launch permission from, or "a… [See Man Page]'
complete -c euca-modify-image-attribute -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-modify-image-attribute -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-modify-image-attribute -s U -l url --description 'compute service endpoint URL .'
complete -c euca-modify-image-attribute -l debug --description 'show debugging output.'
complete -c euca-modify-image-attribute -l debugger --description 'launch interactive debugger on error.'
complete -c euca-modify-image-attribute -l version --description 'show the program\'s version and exit.'
complete -c euca-modify-image-attribute -s I -l access-key-id --description '.'
complete -c euca-modify-image-attribute -s S -l secret-key --description '.'
complete -c euca-modify-image-attribute -s h -l help --description 'show this help message and exit.'

