# euca-attach-volume
# Autogenerated from man page /usr/share/man/man1/euca-attach-volume.1.gz
# using Deroffing man parser
complete -c euca-attach-volume -s i -l instance --description 'instance to attach the volume to (required).'
complete -c euca-attach-volume -s d -l device --description 'device name exposed to the instance (required).'
complete -c euca-attach-volume -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-attach-volume -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-attach-volume -s U -l url --description 'compute service endpoint URL .'
complete -c euca-attach-volume -l debug --description 'show debugging output.'
complete -c euca-attach-volume -l debugger --description 'launch interactive debugger on error.'
complete -c euca-attach-volume -l version --description 'show the program\'s version and exit.'
complete -c euca-attach-volume -s I -l access-key-id --description '.'
complete -c euca-attach-volume -s S -l secret-key --description '.'
complete -c euca-attach-volume -s h -l help --description 'show this help message and exit.'

