# euca-copy-image
# Autogenerated from man page /usr/share/man/man1/euca-copy-image.1.gz
# using Deroffing man parser
complete -c euca-copy-image -s r -l source-region --description 'name of the region to copy the image from (required).'
complete -c euca-copy-image -s s -l source-ami-id --description 'ID of the image to copy (required).'
complete -c euca-copy-image -s n -l name --description 'name to assign the new copy of the image.'
complete -c euca-copy-image -s d -l description --description 'description to assign the new copy of the image.'
complete -c euca-copy-image -s c -l client-token --description 'unique identifier to ensure request idempotency.'
complete -c euca-copy-image -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-copy-image -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-copy-image -s U -l url --description 'compute service endpoint URL.'
complete -c euca-copy-image -s I -l access-key-id --description '.'
complete -c euca-copy-image -s S -l secret-key --description '.'
complete -c euca-copy-image -l debug --description 'show debugging output.'
complete -c euca-copy-image -l debugger --description 'launch interactive debugger on error.'
complete -c euca-copy-image -l version --description 'show the program\'s version and exit.'
complete -c euca-copy-image -s h -l help --description 'show this help message and exit.'

