# euca-download-bundle
# Autogenerated from man page /usr/share/man/man1/euca-download-bundle.1.gz
# using Deroffing man parser
complete -c euca-download-bundle -s b -l bucket --description 'bucket to download the bucket from (required).'
complete -c euca-download-bundle -s m -l manifest --description 'use a local manifest file to figure out what to download.'
complete -c euca-download-bundle -s p -l prefix --description 'download the bundle that begins with a specific prefix (e. g.'
complete -c euca-download-bundle -s d -l directory --description 'The directory to download the parts to.'
complete -c euca-download-bundle -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-download-bundle -s U -l url --description 'storage service endpoint URL.'
complete -c euca-download-bundle -s I -l access-key-id --description '.'
complete -c euca-download-bundle -s S -l secret-key --description '.'
complete -c euca-download-bundle -l debug --description 'show debugging output.'
complete -c euca-download-bundle -l debugger --description 'launch interactive debugger on error.'
complete -c euca-download-bundle -l version --description 'show the program\'s version and exit.'
complete -c euca-download-bundle -s h -l help --description 'show this help message and exit.'

