# euca-describe-tags
# Autogenerated from man page /usr/share/man/man1/euca-describe-tags.1.gz
# using Deroffing man parser
complete -c euca-describe-tags -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-describe-tags -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-describe-tags -s U -l url --description 'compute service endpoint URL .'
complete -c euca-describe-tags -l filter --description 'restrict results to those that meet criteria.'
complete -c euca-describe-tags -l debug --description 'show debugging output.'
complete -c euca-describe-tags -l debugger --description 'launch interactive debugger on error.'
complete -c euca-describe-tags -l version --description 'show the program\'s version and exit.'
complete -c euca-describe-tags -s I -l access-key-id --description '.'
complete -c euca-describe-tags -s S -l secret-key --description '.'
complete -c euca-describe-tags -s h -l help --description 'show this help message and exit allowed filter … [See Man Page]'

