# euca-describe-instances
# Autogenerated from man page /usr/share/man/man1/euca-describe-instances.1.gz
# using Deroffing man parser
complete -c euca-describe-instances -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euca-describe-instances -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euca-describe-instances -s U -l url --description 'compute service endpoint URL .'
complete -c euca-describe-instances -l filter --description 'restrict results to those that meet criteria.'
complete -c euca-describe-instances -l debug --description 'show debugging output.'
complete -c euca-describe-instances -l debugger --description 'launch interactive debugger on error.'
complete -c euca-describe-instances -l version --description 'show the program\'s version and exit.'
complete -c euca-describe-instances -s h -l help --description 'show this help message and exit . SS "allowed filter names:".'
complete -c euca-describe-instances -s I -l access-key-id --description '.'
complete -c euca-describe-instances -s S -l secret-key --description '.'

