# eulb-set-lb-listener-ssl-cert
# Autogenerated from man page /usr/share/man/man1/eulb-set-lb-listener-ssl-cert.1.gz
# using Deroffing man parser
complete -c eulb-set-lb-listener-ssl-cert -s l -l lb-port --description 'port that should use the certificate (required).'
complete -c eulb-set-lb-listener-ssl-cert -s c -l cert-id --description 'ARN for the server certificate to use (required).'
complete -c eulb-set-lb-listener-ssl-cert -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-set-lb-listener-ssl-cert -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-set-lb-listener-ssl-cert -l debug --description 'show debugging output.'
complete -c eulb-set-lb-listener-ssl-cert -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-set-lb-listener-ssl-cert -l version --description 'show the program\'s version and exit.'
complete -c eulb-set-lb-listener-ssl-cert -s I -l access-key-id --description '.'
complete -c eulb-set-lb-listener-ssl-cert -s S -l secret-key --description '.'
complete -c eulb-set-lb-listener-ssl-cert -s h -l help --description 'show this help message and exit.'

