# eulb-attach-lb-to-subnets
# Autogenerated from man page /usr/share/man/man1/eulb-attach-lb-to-subnets.1.gz
# using Deroffing man parser
complete -c eulb-attach-lb-to-subnets -s s -l subnets --description 'IDs of the subnets to add the load balancer to (required).'
complete -c eulb-attach-lb-to-subnets -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-attach-lb-to-subnets -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-attach-lb-to-subnets -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-attach-lb-to-subnets -l debug --description 'show debugging output.'
complete -c eulb-attach-lb-to-subnets -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-attach-lb-to-subnets -l version --description 'show the program\'s version and exit.'
complete -c eulb-attach-lb-to-subnets -s I -l access-key-id --description '.'
complete -c eulb-attach-lb-to-subnets -s S -l secret-key --description '.'
complete -c eulb-attach-lb-to-subnets -s h -l help --description 'show this help message and exit.'

