# eulb-create-lb
# Autogenerated from man page /usr/share/man/man1/eulb-create-lb.1.gz
# using Deroffing man parser
complete -c eulb-create-lb -s s -l subnets --description '[VPC only] subnets the load balancer should run in (required).'
complete -c eulb-create-lb -s z -l availability-zones --description '[Non-VPC only] availability zones the load bala… [See Man Page]'
complete -c eulb-create-lb -s l -l listener --description 'port/protocol settings for the load balancer, w… [See Man Page]'
complete -c eulb-create-lb -s i -l scheme --description '[VPC only] "internal" to make the new load bala… [See Man Page]'
complete -c eulb-create-lb -s g -l security-groups --description '[VPC only] IDs of the security groups to assign… [See Man Page]'
complete -c eulb-create-lb -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-create-lb -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-create-lb -s U -l url --description 'load balancing service endpoint URL.'
complete -c eulb-create-lb -s I -l access-key-id --description '.'
complete -c eulb-create-lb -s S -l secret-key --description '.'
complete -c eulb-create-lb -l debug --description 'show debugging output.'
complete -c eulb-create-lb -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-create-lb -l version --description 'show the program\'s version and exit.'
complete -c eulb-create-lb -s h -l help --description 'show this help message and exit.'

