# eulb-create-lb-listeners
# Autogenerated from man page /usr/share/man/man1/eulb-create-lb-listeners.1.gz
# using Deroffing man parser
complete -c eulb-create-lb-listeners -s l -l listener --description 'port/protocol settings for the load balancer, w… [See Man Page]'
complete -c eulb-create-lb-listeners -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-create-lb-listeners -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-create-lb-listeners -l debug --description 'show debugging output.'
complete -c eulb-create-lb-listeners -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-create-lb-listeners -l version --description 'show the program\'s version and exit.'
complete -c eulb-create-lb-listeners -s I -l access-key-id --description '.'
complete -c eulb-create-lb-listeners -s S -l secret-key --description '.'
complete -c eulb-create-lb-listeners -s h -l help --description 'show this help message and exit.'

