# eulb-describe-instance-health
# Autogenerated from man page /usr/share/man/man1/eulb-describe-instance-health.1.gz
# using Deroffing man parser
complete -c eulb-describe-instance-health -l instances --description 'limit results to specific instances.'
complete -c eulb-describe-instance-health -l show-long --description 'show all of the instances\' info.'
complete -c eulb-describe-instance-health -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-describe-instance-health -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-describe-instance-health -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-describe-instance-health -l debug --description 'show debugging output.'
complete -c eulb-describe-instance-health -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-describe-instance-health -l version --description 'show the program\'s version and exit.'
complete -c eulb-describe-instance-health -s I -l access-key-id --description '.'
complete -c eulb-describe-instance-health -s S -l secret-key --description '.'
complete -c eulb-describe-instance-health -s h -l help --description 'show this help message and exit.'

