# eulb-describe-lbs
# Autogenerated from man page /usr/share/man/man1/eulb-describe-lbs.1.gz
# using Deroffing man parser
complete -c eulb-describe-lbs -l show-long --description 'show all of the load balancers\' info.'
complete -c eulb-describe-lbs -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-describe-lbs -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-describe-lbs -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-describe-lbs -l debug --description 'show debugging output.'
complete -c eulb-describe-lbs -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-describe-lbs -l version --description 'show the program\'s version and exit.'
complete -c eulb-describe-lbs -s I -l access-key-id --description '.'
complete -c eulb-describe-lbs -s S -l secret-key --description '.'
complete -c eulb-describe-lbs -s h -l help --description 'show this help message and exit.'

