# eulb-configure-healthcheck
# Autogenerated from man page /usr/share/man/man1/eulb-configure-healthcheck.1.gz
# using Deroffing man parser
complete -c eulb-configure-healthcheck -l healthy-threshold --description 'number of consecutive successful health checks … [See Man Page]'
complete -c eulb-configure-healthcheck -l interval --description 'approximate interval between health checks (required).'
complete -c eulb-configure-healthcheck -s t -l target --description 'connection target for health checks (required).'
complete -c eulb-configure-healthcheck -l timeout --description 'maximum health check duration (required).'
complete -c eulb-configure-healthcheck -l unhealthy-threshold --description 'number of consecutive failed health checks that… [See Man Page]'
complete -c eulb-configure-healthcheck -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-configure-healthcheck -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-configure-healthcheck -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-configure-healthcheck -l debug --description 'show debugging output.'
complete -c eulb-configure-healthcheck -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-configure-healthcheck -l version --description 'show the program\'s version and exit.'
complete -c eulb-configure-healthcheck -s I -l access-key-id --description '.'
complete -c eulb-configure-healthcheck -s S -l secret-key --description '.'
complete -c eulb-configure-healthcheck -s h -l help --description 'show this help message and exit.'

