# eulb-apply-security-groups-to-lb
# Autogenerated from man page /usr/share/man/man1/eulb-apply-security-groups-to-lb.1.gz
# using Deroffing man parser
complete -c eulb-apply-security-groups-to-lb -s g -l security-groups --description 'security groups to associate the load balancer with (required).'
complete -c eulb-apply-security-groups-to-lb -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-apply-security-groups-to-lb -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-apply-security-groups-to-lb -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-apply-security-groups-to-lb -l debug --description 'show debugging output.'
complete -c eulb-apply-security-groups-to-lb -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-apply-security-groups-to-lb -l version --description 'show the program\'s version and exit.'
complete -c eulb-apply-security-groups-to-lb -s I -l access-key-id --description '.'
complete -c eulb-apply-security-groups-to-lb -s S -l secret-key --description '.'
complete -c eulb-apply-security-groups-to-lb -s h -l help --description 'show this help message and exit.'

