# eulb-describe-lb-policies
# Autogenerated from man page /usr/share/man/man1/eulb-describe-lb-policies.1.gz
# using Deroffing man parser
complete -c eulb-describe-lb-policies -s p -l policy-names --description 'limit results to specific policies.'
complete -c eulb-describe-lb-policies -l show-long --description 'show all of the policies\' info.'
complete -c eulb-describe-lb-policies -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-describe-lb-policies -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-describe-lb-policies -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-describe-lb-policies -l debug --description 'show debugging output.'
complete -c eulb-describe-lb-policies -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-describe-lb-policies -l version --description 'show the program\'s version and exit.'
complete -c eulb-describe-lb-policies -s I -l access-key-id --description '.'
complete -c eulb-describe-lb-policies -s S -l secret-key --description '.'
complete -c eulb-describe-lb-policies -s h -l help --description 'show this help message and exit.'

