# eulb-register-instances-with-lb
# Autogenerated from man page /usr/share/man/man1/eulb-register-instances-with-lb.1.gz
# using Deroffing man parser
complete -c eulb-register-instances-with-lb -l instances --description 'IDs of the instances to register with the load … [See Man Page]'
complete -c eulb-register-instances-with-lb -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-register-instances-with-lb -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-register-instances-with-lb -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-register-instances-with-lb -l debug --description 'show debugging output.'
complete -c eulb-register-instances-with-lb -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-register-instances-with-lb -l version --description 'show the program\'s version and exit.'
complete -c eulb-register-instances-with-lb -s I -l access-key-id --description '.'
complete -c eulb-register-instances-with-lb -s S -l secret-key --description '.'
complete -c eulb-register-instances-with-lb -s h -l help --description 'show this help message and exit.'

