# eulb-create-app-cookie-stickiness-policy
# Autogenerated from man page /usr/share/man/man1/eulb-create-app-cookie-stickiness-policy.1.gz
# using Deroffing man parser
complete -c eulb-create-app-cookie-stickiness-policy -s c -l cookie-name --description 'name of the cookie used for stickiness (required).'
complete -c eulb-create-app-cookie-stickiness-policy -s p -l policy-name --description 'name of the new policy (required).'
complete -c eulb-create-app-cookie-stickiness-policy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-create-app-cookie-stickiness-policy -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-create-app-cookie-stickiness-policy -l debug --description 'show debugging output.'
complete -c eulb-create-app-cookie-stickiness-policy -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-create-app-cookie-stickiness-policy -l version --description 'show the program\'s version and exit.'
complete -c eulb-create-app-cookie-stickiness-policy -s I -l access-key-id --description '.'
complete -c eulb-create-app-cookie-stickiness-policy -s S -l secret-key --description '.'
complete -c eulb-create-app-cookie-stickiness-policy -s h -l help --description 'show this help message and exit.'

