# eulb-create-lb-policy
# Autogenerated from man page /usr/share/man/man1/eulb-create-lb-policy.1.gz
# using Deroffing man parser
complete -c eulb-create-lb-policy -l policy-name --description 'name of the new policy (required).'
complete -c eulb-create-lb-policy -l policy-type --description 'type of the new policy.'
complete -c eulb-create-lb-policy -s a -l attribute --description 'name and value for each attribute associated wi… [See Man Page]'
complete -c eulb-create-lb-policy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-create-lb-policy -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-create-lb-policy -l debug --description 'show debugging output.'
complete -c eulb-create-lb-policy -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-create-lb-policy -l version --description 'show the program\'s version and exit.'
complete -c eulb-create-lb-policy -s I -l access-key-id --description '.'
complete -c eulb-create-lb-policy -s S -l secret-key --description '.'
complete -c eulb-create-lb-policy -s h -l help --description 'show this help message and exit.'

