# eulb-set-lb-policies-for-backend-server
# Autogenerated from man page /usr/share/man/man1/eulb-set-lb-policies-for-backend-server.1.gz
# using Deroffing man parser
complete -c eulb-set-lb-policies-for-backend-server -s i -l instance-port --description 'port number of the back end server (required).'
complete -c eulb-set-lb-policies-for-backend-server -s p -l policy-names --description 'list of policies to associate with the back end… [See Man Page]'
complete -c eulb-set-lb-policies-for-backend-server -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-set-lb-policies-for-backend-server -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-set-lb-policies-for-backend-server -l debug --description 'show debugging output.'
complete -c eulb-set-lb-policies-for-backend-server -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-set-lb-policies-for-backend-server -l version --description 'show the program\'s version and exit.'
complete -c eulb-set-lb-policies-for-backend-server -s I -l access-key-id --description '.'
complete -c eulb-set-lb-policies-for-backend-server -s S -l secret-key --description '.'
complete -c eulb-set-lb-policies-for-backend-server -s h -l help --description 'show this help message and exit.'

