# eulb-delete-lb
# Autogenerated from man page /usr/share/man/man1/eulb-delete-lb.1.gz
# using Deroffing man parser
complete -c eulb-delete-lb -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-delete-lb -s U -l url --description 'load balancing service endpoint URL.'
complete -c eulb-delete-lb -s I -l access-key-id --description '.'
complete -c eulb-delete-lb -s S -l secret-key --description '.'
complete -c eulb-delete-lb -l debug --description 'show debugging output.'
complete -c eulb-delete-lb -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-delete-lb -l version --description 'show the program\'s version and exit.'
complete -c eulb-delete-lb -s h -l help --description 'show this help message and exit.'

