# eulb-detach-lb-from-subnets
# Autogenerated from man page /usr/share/man/man1/eulb-detach-lb-from-subnets.1.gz
# using Deroffing man parser
complete -c eulb-detach-lb-from-subnets -s s -l subnets --description 'IDs of the subnets to remove the load balancer from (required).'
complete -c eulb-detach-lb-from-subnets -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-detach-lb-from-subnets -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-detach-lb-from-subnets -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-detach-lb-from-subnets -l debug --description 'show debugging output.'
complete -c eulb-detach-lb-from-subnets -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-detach-lb-from-subnets -l version --description 'show the program\'s version and exit.'
complete -c eulb-detach-lb-from-subnets -s I -l access-key-id --description '.'
complete -c eulb-detach-lb-from-subnets -s S -l secret-key --description '.'
complete -c eulb-detach-lb-from-subnets -s h -l help --description 'show this help message and exit.'

