# eulb-set-lb-policies-of-listener
# Autogenerated from man page /usr/share/man/man1/eulb-set-lb-policies-of-listener.1.gz
# using Deroffing man parser
complete -c eulb-set-lb-policies-of-listener -s l -l lb-port --description 'port of the listener to modify (required).'
complete -c eulb-set-lb-policies-of-listener -s p -l policy-names --description 'list of policies to associate with the listener (required).'
complete -c eulb-set-lb-policies-of-listener -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-set-lb-policies-of-listener -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-set-lb-policies-of-listener -l debug --description 'show debugging output.'
complete -c eulb-set-lb-policies-of-listener -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-set-lb-policies-of-listener -l version --description 'show the program\'s version and exit.'
complete -c eulb-set-lb-policies-of-listener -s I -l access-key-id --description '.'
complete -c eulb-set-lb-policies-of-listener -s S -l secret-key --description '.'
complete -c eulb-set-lb-policies-of-listener -s h -l help --description 'show this help message and exit.'

