# eulb-disable-zones-for-lb
# Autogenerated from man page /usr/share/man/man1/eulb-disable-zones-for-lb.1.gz
# using Deroffing man parser
complete -c eulb-disable-zones-for-lb -s z -l availability-zones --description 'availability zones to remove the load balancer from (required).'
complete -c eulb-disable-zones-for-lb -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eulb-disable-zones-for-lb -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eulb-disable-zones-for-lb -s U -l url --description 'load balancing service endpoint URL .'
complete -c eulb-disable-zones-for-lb -l debug --description 'show debugging output.'
complete -c eulb-disable-zones-for-lb -l debugger --description 'launch interactive debugger on error.'
complete -c eulb-disable-zones-for-lb -l version --description 'show the program\'s version and exit.'
complete -c eulb-disable-zones-for-lb -s I -l access-key-id --description '.'
complete -c eulb-disable-zones-for-lb -s S -l secret-key --description '.'
complete -c eulb-disable-zones-for-lb -s h -l help --description 'show this help message and exit.'

