# euscale-delete-launch-config
# Autogenerated from man page /usr/share/man/man1/euscale-delete-launch-config.1.gz
# using Deroffing man parser
complete -c euscale-delete-launch-config -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-delete-launch-config -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-delete-launch-config -l debug --description 'show debugging output.'
complete -c euscale-delete-launch-config -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-delete-launch-config -l version --description 'show the program\'s version and exit.'
complete -c euscale-delete-launch-config -s I -l access-key-id --description '.'
complete -c euscale-delete-launch-config -s S -l secret-key --description '.'
complete -c euscale-delete-launch-config -s h -l help --description 'show this help message and exit.'

