# euscale-put-scaling-policy
# Autogenerated from man page /usr/share/man/man1/euscale-put-scaling-policy.1.gz
# using Deroffing man parser
complete -c euscale-put-scaling-policy -s g -l auto-scaling-group --description 'name of the auto-scaling group the policy is as… [See Man Page]'
complete -c euscale-put-scaling-policy -s a -l adjustment --description 'amount to scale the group\'s capacity of the group.'
complete -c euscale-put-scaling-policy -s t -l type --description 'whether the adjustment is the new desired size … [See Man Page]'
complete -c euscale-put-scaling-policy -l cooldown --description 'waiting period after successful auto-scaling ac… [See Man Page]'
complete -c euscale-put-scaling-policy -s s -l min-adjustment-step --description 'for a PercentChangeInCapacity type policy, guar… [See Man Page]'
complete -c euscale-put-scaling-policy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-put-scaling-policy -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-put-scaling-policy -l debug --description 'show debugging output.'
complete -c euscale-put-scaling-policy -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-put-scaling-policy -l version --description 'show the program\'s version and exit.'
complete -c euscale-put-scaling-policy -s I -l access-key-id --description '.'
complete -c euscale-put-scaling-policy -s S -l secret-key --description '.'
complete -c euscale-put-scaling-policy -s h -l help --description 'show this help message and exit.'

