# euscale-delete-policy
# Autogenerated from man page /usr/share/man/man1/euscale-delete-policy.1.gz
# using Deroffing man parser
complete -c euscale-delete-policy -s g -l auto-scaling-group --description 'name of the auto-scaling group the policy is as… [See Man Page]'
complete -c euscale-delete-policy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-delete-policy -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-delete-policy -l debug --description 'show debugging output.'
complete -c euscale-delete-policy -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-delete-policy -l version --description 'show the program\'s version and exit.'
complete -c euscale-delete-policy -s I -l access-key-id --description '.'
complete -c euscale-delete-policy -s S -l secret-key --description '.'
complete -c euscale-delete-policy -s h -l help --description 'show this help message and exit.'

