# euscale-disable-metrics-collection
# Autogenerated from man page /usr/share/man/man1/euscale-disable-metrics-collection.1.gz
# using Deroffing man parser
complete -c euscale-disable-metrics-collection -s m -l metrics --description 'list of metrics to disable (default: all metrics).'
complete -c euscale-disable-metrics-collection -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-disable-metrics-collection -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-disable-metrics-collection -l debug --description 'show debugging output.'
complete -c euscale-disable-metrics-collection -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-disable-metrics-collection -l version --description 'show the program\'s version and exit.'
complete -c euscale-disable-metrics-collection -s I -l access-key-id --description '.'
complete -c euscale-disable-metrics-collection -s S -l secret-key --description '.'
complete -c euscale-disable-metrics-collection -s h -l help --description 'show this help message and exit.'

