# euscale-describe-scaling-activities
# Autogenerated from man page /usr/share/man/man1/euscale-describe-scaling-activities.1.gz
# using Deroffing man parser
complete -c euscale-describe-scaling-activities -s g -l auto-scaling-group --description 'name of an Auto Scaling group by which to filter the request.'
complete -c euscale-describe-scaling-activities -l show-long --description 'show all of the activities\' info.'
complete -c euscale-describe-scaling-activities -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euscale-describe-scaling-activities -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-describe-scaling-activities -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-describe-scaling-activities -l debug --description 'show debugging output.'
complete -c euscale-describe-scaling-activities -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-describe-scaling-activities -l version --description 'show the program\'s version and exit.'
complete -c euscale-describe-scaling-activities -s I -l access-key-id --description '.'
complete -c euscale-describe-scaling-activities -s S -l secret-key --description '.'
complete -c euscale-describe-scaling-activities -s h -l help --description 'show this help message and exit.'

