# euscale-set-desired-capacity
# Autogenerated from man page /usr/share/man/man1/euscale-set-desired-capacity.1.gz
# using Deroffing man parser
complete -c euscale-set-desired-capacity -s c -l desired-capacity --description 'new capacity setting for the group (required).'
complete -c euscale-set-desired-capacity -s h -l honor-cooldown --description 'reject the request if the group is in cooldown … [See Man Page]'
complete -c euscale-set-desired-capacity -s H -l no-honor-cooldown --description 'override any cooldown period (this is the default).'
complete -c euscale-set-desired-capacity -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-set-desired-capacity -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-set-desired-capacity -l debug --description 'show debugging output.'
complete -c euscale-set-desired-capacity -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-set-desired-capacity -l version --description 'show the program\'s version and exit.'
complete -c euscale-set-desired-capacity -s I -l access-key-id --description '.'
complete -c euscale-set-desired-capacity -s S -l secret-key --description '.'
complete -c euscale-set-desired-capacity -l help --description 'show this help message and exit.'

