# euscale-describe-policies
# Autogenerated from man page /usr/share/man/man1/euscale-describe-policies.1.gz
# using Deroffing man parser
complete -c euscale-describe-policies -l show-long --description 'show all of the policies\' info.'
complete -c euscale-describe-policies -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euscale-describe-policies -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-describe-policies -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-describe-policies -l debug --description 'show debugging output.'
complete -c euscale-describe-policies -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-describe-policies -l version --description 'show the program\'s version and exit.'
complete -c euscale-describe-policies -s g -l auto-scaling-group --description '.'
complete -c euscale-describe-policies -s I -l access-key-id --description '.'
complete -c euscale-describe-policies -s S -l secret-key --description '.'
complete -c euscale-describe-policies -s h -l help --description 'show this help message and exit.'

