# euscale-delete-notification-configuration
# Autogenerated from man page /usr/share/man/man1/euscale-delete-notification-configuration.1.gz
# using Deroffing man parser
complete -c euscale-delete-notification-configuration -s t -l topic-arn --description 'ARN of the SNS topic associated with the config… [See Man Page]'
complete -c euscale-delete-notification-configuration -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-delete-notification-configuration -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-delete-notification-configuration -l debug --description 'show debugging output.'
complete -c euscale-delete-notification-configuration -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-delete-notification-configuration -l version --description 'show the program\'s version and exit.'
complete -c euscale-delete-notification-configuration -s I -l access-key-id --description '.'
complete -c euscale-delete-notification-configuration -s S -l secret-key --description '.'
complete -c euscale-delete-notification-configuration -s h -l help --description 'show this help message and exit.'

