# euscale-describe-scheduled-actions
# Autogenerated from man page /usr/share/man/man1/euscale-describe-scheduled-actions.1.gz
# using Deroffing man parser
complete -c euscale-describe-scheduled-actions -l start-time --description 'earliest start time to return scheduled actions for.'
complete -c euscale-describe-scheduled-actions -l end-time --description 'latest start time to return scheduled actions for.'
complete -c euscale-describe-scheduled-actions -l show-long --description 'show all of the scheduled actions\' info.'
complete -c euscale-describe-scheduled-actions -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euscale-describe-scheduled-actions -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-describe-scheduled-actions -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-describe-scheduled-actions -l debug --description 'show debugging output.'
complete -c euscale-describe-scheduled-actions -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-describe-scheduled-actions -l version --description 'show the program\'s version and exit.'
complete -c euscale-describe-scheduled-actions -s g -l group --description '.'
complete -c euscale-describe-scheduled-actions -s I -l access-key-id --description '.'
complete -c euscale-describe-scheduled-actions -s S -l secret-key --description '.'
complete -c euscale-describe-scheduled-actions -s h -l help --description 'show this help message and exit.'

