# euscale-put-scheduled-update-group-action
# Autogenerated from man page /usr/share/man/man1/euscale-put-scheduled-update-group-action.1.gz
# using Deroffing man parser
complete -c euscale-put-scheduled-update-group-action -s g -l auto-scaling-group --description 'auto-scaling group the new action should affect (required).'
complete -c euscale-put-scheduled-update-group-action -s b -l start-time --description 'time for this action to start.'
complete -c euscale-put-scheduled-update-group-action -s e -l end-time --description 'time for this action to end.'
complete -c euscale-put-scheduled-update-group-action -s r -l recurrence --description 'time when recurring future actions will start, … [See Man Page]'
complete -c euscale-put-scheduled-update-group-action -l desired-capacity --description 'new capacity setting for the group.'
complete -c euscale-put-scheduled-update-group-action -l max-size --description 'maximum number of instances to allow in the group.'
complete -c euscale-put-scheduled-update-group-action -l min-size --description 'minimum number of instances to allow in the group.'
complete -c euscale-put-scheduled-update-group-action -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-put-scheduled-update-group-action -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-put-scheduled-update-group-action -l debug --description 'show debugging output.'
complete -c euscale-put-scheduled-update-group-action -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-put-scheduled-update-group-action -l version --description 'show the program\'s version and exit.'
complete -c euscale-put-scheduled-update-group-action -s I -l access-key-id --description '.'
complete -c euscale-put-scheduled-update-group-action -s S -l secret-key --description '.'
complete -c euscale-put-scheduled-update-group-action -s h -l help --description 'show this help message and exit.'

