# euscale-execute-policy
# Autogenerated from man page /usr/share/man/man1/euscale-execute-policy.1.gz
# using Deroffing man parser
complete -c euscale-execute-policy -s g -l auto-scaling-group --description 'name or ARN of the auto-scaling group.'
complete -c euscale-execute-policy -s h -l honor-cooldown --description 'reject the request if the group is in cooldown … [See Man Page]'
complete -c euscale-execute-policy -s H -l no-honor-cooldown --description 'override any cooldown period (this is the default).'
complete -c euscale-execute-policy -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-execute-policy -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-execute-policy -l debug --description 'show debugging output.'
complete -c euscale-execute-policy -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-execute-policy -l version --description 'show the program\'s version and exit.'
complete -c euscale-execute-policy -s I -l access-key-id --description '.'
complete -c euscale-execute-policy -s S -l secret-key --description '.'
complete -c euscale-execute-policy -l help --description 'show this help message and exit.'

