# euscale-describe-launch-configs
# Autogenerated from man page /usr/share/man/man1/euscale-describe-launch-configs.1.gz
# using Deroffing man parser
complete -c euscale-describe-launch-configs -l show-long --description 'show all of the launch configurations\' info.'
complete -c euscale-describe-launch-configs -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euscale-describe-launch-configs -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-describe-launch-configs -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-describe-launch-configs -l debug --description 'show debugging output.'
complete -c euscale-describe-launch-configs -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-describe-launch-configs -l version --description 'show the program\'s version and exit.'
complete -c euscale-describe-launch-configs -s I -l access-key-id --description '.'
complete -c euscale-describe-launch-configs -s S -l secret-key --description '.'
complete -c euscale-describe-launch-configs -s h -l help --description 'show this help message and exit.'

