# euscale-delete-scheduled-action
# Autogenerated from man page /usr/share/man/man1/euscale-delete-scheduled-action.1.gz
# using Deroffing man parser
complete -c euscale-delete-scheduled-action -s g -l auto-scaling-group --description 'name of the auto-scaling group the scheduled ac… [See Man Page]'
complete -c euscale-delete-scheduled-action -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-delete-scheduled-action -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-delete-scheduled-action -l debug --description 'show debugging output.'
complete -c euscale-delete-scheduled-action -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-delete-scheduled-action -l version --description 'show the program\'s version and exit.'
complete -c euscale-delete-scheduled-action -s I -l access-key-id --description '.'
complete -c euscale-delete-scheduled-action -s S -l secret-key --description '.'
complete -c euscale-delete-scheduled-action -s h -l help --description 'show this help message and exit.'

