# euscale-terminate-instance-in-auto-scaling-group
# Autogenerated from man page /usr/share/man/man1/euscale-terminate-instance-in-auto-scaling-group.1.gz
# using Deroffing man parser
complete -c euscale-terminate-instance-in-auto-scaling-group -s d -l decrement-desired-capacity --description 'also reduce the desired capacity of the auto-sc… [See Man Page]'
complete -c euscale-terminate-instance-in-auto-scaling-group -s D -l no-decrement-desired-capacity --description 'leave the auto-scaling group\'s desired capacity as-is.'
complete -c euscale-terminate-instance-in-auto-scaling-group -l show-long --description 'show extra info about the instance being terminated.'
complete -c euscale-terminate-instance-in-auto-scaling-group -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euscale-terminate-instance-in-auto-scaling-group -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-terminate-instance-in-auto-scaling-group -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-terminate-instance-in-auto-scaling-group -l debug --description 'show debugging output.'
complete -c euscale-terminate-instance-in-auto-scaling-group -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-terminate-instance-in-auto-scaling-group -l version --description 'show the program\'s version and exit.'
complete -c euscale-terminate-instance-in-auto-scaling-group -s I -l access-key-id --description '.'
complete -c euscale-terminate-instance-in-auto-scaling-group -s S -l secret-key --description '.'
complete -c euscale-terminate-instance-in-auto-scaling-group -s h -l help --description 'show this help message and exit.'

