# euscale-describe-notification-configurations
# Autogenerated from man page /usr/share/man/man1/euscale-describe-notification-configurations.1.gz
# using Deroffing man parser
complete -c euscale-describe-notification-configurations -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euscale-describe-notification-configurations -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-describe-notification-configurations -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-describe-notification-configurations -l debug --description 'show debugging output.'
complete -c euscale-describe-notification-configurations -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-describe-notification-configurations -l version --description 'show the program\'s version and exit.'
complete -c euscale-describe-notification-configurations -s I -l access-key-id --description '.'
complete -c euscale-describe-notification-configurations -s S -l secret-key --description '.'
complete -c euscale-describe-notification-configurations -s h -l help --description 'show this help message and exit.'

