# euscale-delete-auto-scaling-group
# Autogenerated from man page /usr/share/man/man1/euscale-delete-auto-scaling-group.1.gz
# using Deroffing man parser
complete -c euscale-delete-auto-scaling-group -s d -l force-delete --description 'delete the group and all of its instances witho… [See Man Page]'
complete -c euscale-delete-auto-scaling-group -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-delete-auto-scaling-group -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-delete-auto-scaling-group -l debug --description 'show debugging output.'
complete -c euscale-delete-auto-scaling-group -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-delete-auto-scaling-group -l version --description 'show the program\'s version and exit.'
complete -c euscale-delete-auto-scaling-group -s I -l access-key-id --description '.'
complete -c euscale-delete-auto-scaling-group -s S -l secret-key --description '.'
complete -c euscale-delete-auto-scaling-group -s h -l help --description 'show this help message and exit.'

