# euscale-set-instance-health
# Autogenerated from man page /usr/share/man/man1/euscale-set-instance-health.1.gz
# using Deroffing man parser
complete -c euscale-set-instance-health -s s -l status --description 'new status (required).'
complete -c euscale-set-instance-health -l respect-grace-period --description 'respect the associated auto-scaling group\'s gra… [See Man Page]'
complete -c euscale-set-instance-health -l no-respect-grace-period --description 'ignore the associated auto-scaling group\'s grac… [See Man Page]'
complete -c euscale-set-instance-health -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-set-instance-health -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-set-instance-health -l debug --description 'show debugging output.'
complete -c euscale-set-instance-health -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-set-instance-health -l version --description 'show the program\'s version and exit.'
complete -c euscale-set-instance-health -s I -l access-key-id --description '.'
complete -c euscale-set-instance-health -s S -l secret-key --description '.'
complete -c euscale-set-instance-health -s h -l help --description 'show this help message and exit.'

