# euscale-create-or-update-tags
# Autogenerated from man page /usr/share/man/man1/euscale-create-or-update-tags.1.gz
# using Deroffing man parser
complete -c euscale-create-or-update-tags -l tag --description 'attributes of a tag to affect.'
complete -c euscale-create-or-update-tags -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-create-or-update-tags -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-create-or-update-tags -l debug --description 'show debugging output.'
complete -c euscale-create-or-update-tags -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-create-or-update-tags -l version --description 'show the program\'s version and exit.'
complete -c euscale-create-or-update-tags -s I -l access-key-id --description '.'
complete -c euscale-create-or-update-tags -s S -l secret-key --description '.'
complete -c euscale-create-or-update-tags -s h -l help --description 'show this help message and exit.'

