# euscale-resume-processes
# Autogenerated from man page /usr/share/man/man1/euscale-resume-processes.1.gz
# using Deroffing man parser
complete -c euscale-resume-processes -l processes --description 'comma-separated list of auto-scaling processes … [See Man Page]'
complete -c euscale-resume-processes -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-resume-processes -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-resume-processes -l debug --description 'show debugging output.'
complete -c euscale-resume-processes -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-resume-processes -l version --description 'show the program\'s version and exit.'
complete -c euscale-resume-processes -s I -l access-key-id --description '.'
complete -c euscale-resume-processes -s S -l secret-key --description '.'
complete -c euscale-resume-processes -s h -l help --description 'show this help message and exit.'

