# euscale-describe-auto-scaling-instances
# Autogenerated from man page /usr/share/man/man1/euscale-describe-auto-scaling-instances.1.gz
# using Deroffing man parser
complete -c euscale-describe-auto-scaling-instances -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euscale-describe-auto-scaling-instances -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-describe-auto-scaling-instances -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-describe-auto-scaling-instances -l debug --description 'show debugging output.'
complete -c euscale-describe-auto-scaling-instances -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-describe-auto-scaling-instances -l version --description 'show the program\'s version and exit.'
complete -c euscale-describe-auto-scaling-instances -s I -l access-key-id --description '.'
complete -c euscale-describe-auto-scaling-instances -s S -l secret-key --description '.'
complete -c euscale-describe-auto-scaling-instances -s h -l help --description 'show this help message and exit.'

