# euscale-update-auto-scaling-group
# Autogenerated from man page /usr/share/man/man1/euscale-update-auto-scaling-group.1.gz
# using Deroffing man parser
complete -c euscale-update-auto-scaling-group -l default-cooldown --description 'amount of time, in seconds, after a scaling act… [See Man Page]'
complete -c euscale-update-auto-scaling-group -l desired-capacity --description 'number of running instances the group should contain.'
complete -c euscale-update-auto-scaling-group -l grace-period --description 'number of seconds to wait before starting healt… [See Man Page]'
complete -c euscale-update-auto-scaling-group -l health-check-type --description 'service to obtain health check status from.'
complete -c euscale-update-auto-scaling-group -s l -l launch-configuration --description 'name of the launch configuration to use with th… [See Man Page]'
complete -c euscale-update-auto-scaling-group -s M -l max-size --description 'maximum group size (required).'
complete -c euscale-update-auto-scaling-group -s m -l min-size --description 'minimum group size (required).'
complete -c euscale-update-auto-scaling-group -l placement-group --description 'placement group in which to launch new instances.'
complete -c euscale-update-auto-scaling-group -l termination-policies --description 'ordered list of termination policies.'
complete -c euscale-update-auto-scaling-group -l vpc-zone-identifier --description 'comma-separated list of subnet identifiers.'
complete -c euscale-update-auto-scaling-group -s z -l availability-zones --description 'comma-separated list of availability zones for … [See Man Page]'
complete -c euscale-update-auto-scaling-group -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euscale-update-auto-scaling-group -s U -l url --description 'auto-scaling service endpoint URL .'
complete -c euscale-update-auto-scaling-group -l debug --description 'show debugging output.'
complete -c euscale-update-auto-scaling-group -l debugger --description 'launch interactive debugger on error.'
complete -c euscale-update-auto-scaling-group -l version --description 'show the program\'s version and exit.'
complete -c euscale-update-auto-scaling-group -s I -l access-key-id --description '.'
complete -c euscale-update-auto-scaling-group -s S -l secret-key --description '.'
complete -c euscale-update-auto-scaling-group -s h -l help --description 'show this help message and exit.'

