# eustore-describe-images
# Autogenerated from man page /usr/share/man/man1/eustore-describe-images.1.gz
# using Deroffing man parser
complete -c eustore-describe-images -s v -l verbose --description 'display more information about images than the default.'
complete -c eustore-describe-images -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c eustore-describe-images -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c eustore-describe-images -s U -l url --description 'EuStore service URL.'
complete -c eustore-describe-images -l debug --description 'show debugging output.'
complete -c eustore-describe-images -l debugger --description 'launch interactive debugger on error.'
complete -c eustore-describe-images -l version --description 'show the program\'s version and exit.'
complete -c eustore-describe-images -s h -l help --description 'show this help message and exit.'

