# euwatch-list-metrics
# Autogenerated from man page /usr/share/man/man1/euwatch-list-metrics.1.gz
# using Deroffing man parser
complete -c euwatch-list-metrics -s d -l dimensions --description 'limit results to metrics with specific dimensions.'
complete -c euwatch-list-metrics -s m -l metric-name --description 'limit results to a specific metric.'
complete -c euwatch-list-metrics -s n -l namespace --description 'limit results to metrics in a specific namespace.'
complete -c euwatch-list-metrics -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euwatch-list-metrics -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euwatch-list-metrics -s U -l url --description 'instance monitoring service endpoint URL .'
complete -c euwatch-list-metrics -l debug --description 'show debugging output.'
complete -c euwatch-list-metrics -l debugger --description 'launch interactive debugger on error.'
complete -c euwatch-list-metrics -l version --description 'show the program\'s version and exit.'
complete -c euwatch-list-metrics -s I -l access-key-id --description '.'
complete -c euwatch-list-metrics -s S -l secret-key --description '.'
complete -c euwatch-list-metrics -s h -l help --description 'show this help message and exit.'

