# euwatch-put-data
# Autogenerated from man page /usr/share/man/man1/euwatch-put-data.1.gz
# using Deroffing man parser
complete -c euwatch-put-data -s m -l metric-name --description 'name of the metric to add data points to (required).'
complete -c euwatch-put-data -s n -l namespace --description 'the metric\'s namespace (required).'
complete -c euwatch-put-data -s v -l value --description 'data value for the metric.'
complete -c euwatch-put-data -s s -l statistic-values -l statisticValues --description 'statistic values for the metric.'
complete -c euwatch-put-data -s d -l dimensions --description 'the dimensions of the metric to add data points to.'
complete -c euwatch-put-data -s t -l timestamp --description 'timestamp of the data point.'
complete -c euwatch-put-data -s u -l unit --description 'unit the metric is being reported in.'
complete -c euwatch-put-data -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euwatch-put-data -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euwatch-put-data -s U -l url --description 'instance monitoring service endpoint URL .'
complete -c euwatch-put-data -l debug --description 'show debugging output.'
complete -c euwatch-put-data -l debugger --description 'launch interactive debugger on error.'
complete -c euwatch-put-data -l version --description 'show the program\'s version and exit.'
complete -c euwatch-put-data -s I -l access-key-id --description '.'
complete -c euwatch-put-data -s S -l secret-key --description '.'
complete -c euwatch-put-data -s h -l help --description 'show this help message and exit.'

