# euwatch-set-alarm-state
# Autogenerated from man page /usr/share/man/man1/euwatch-set-alarm-state.1.gz
# using Deroffing man parser
complete -c euwatch-set-alarm-state -l state-value --description 'state to set the alarm to (required).'
complete -c euwatch-set-alarm-state -l state-reason --description 'human-readable reason why the alarm was set to … [See Man Page]'
complete -c euwatch-set-alarm-state -l state-reason-data --description 'JSON-formatted reason why the alarm was set to this state.'
complete -c euwatch-set-alarm-state -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euwatch-set-alarm-state -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euwatch-set-alarm-state -s U -l url --description 'instance monitoring service endpoint URL .'
complete -c euwatch-set-alarm-state -l debug --description 'show debugging output.'
complete -c euwatch-set-alarm-state -l debugger --description 'launch interactive debugger on error.'
complete -c euwatch-set-alarm-state -l version --description 'show the program\'s version and exit.'
complete -c euwatch-set-alarm-state -s I -l access-key-id --description '.'
complete -c euwatch-set-alarm-state -s S -l secret-key --description '.'
complete -c euwatch-set-alarm-state -s h -l help --description 'show this help message and exit.'

