# euwatch-delete-alarms
# Autogenerated from man page /usr/share/man/man1/euwatch-delete-alarms.1.gz
# using Deroffing man parser
complete -c euwatch-delete-alarms -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euwatch-delete-alarms -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euwatch-delete-alarms -s U -l url --description 'instance monitoring service endpoint URL .'
complete -c euwatch-delete-alarms -l debug --description 'show debugging output.'
complete -c euwatch-delete-alarms -l debugger --description 'launch interactive debugger on error.'
complete -c euwatch-delete-alarms -l version --description 'show the program\'s version and exit.'
complete -c euwatch-delete-alarms -s I -l access-key-id --description '.'
complete -c euwatch-delete-alarms -s S -l secret-key --description '.'
complete -c euwatch-delete-alarms -s h -l help --description 'show this help message and exit.'

