# euwatch-describe-alarm-history
# Autogenerated from man page /usr/share/man/man1/euwatch-describe-alarm-history.1.gz
# using Deroffing man parser
complete -c euwatch-describe-alarm-history -l end-date --description 'limit results to history before a given point in time.'
complete -c euwatch-describe-alarm-history -l history-item-type --description 'limit results to specific history item types.'
complete -c euwatch-describe-alarm-history -l show-long --description 'show detailed event data as machine-readable JSON.'
complete -c euwatch-describe-alarm-history -l start-date --description 'limit results to history after a given point in time.'
complete -c euwatch-describe-alarm-history -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euwatch-describe-alarm-history -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euwatch-describe-alarm-history -s U -l url --description 'instance monitoring service endpoint URL .'
complete -c euwatch-describe-alarm-history -l debug --description 'show debugging output.'
complete -c euwatch-describe-alarm-history -l debugger --description 'launch interactive debugger on error.'
complete -c euwatch-describe-alarm-history -l version --description 'show the program\'s version and exit.'
complete -c euwatch-describe-alarm-history -s I -l access-key-id --description '.'
complete -c euwatch-describe-alarm-history -s S -l secret-key --description '.'
complete -c euwatch-describe-alarm-history -s h -l help --description 'show this help message and exit.'

