# euwatch-describe-alarms
# Autogenerated from man page /usr/share/man/man1/euwatch-describe-alarms.1.gz
# using Deroffing man parser
complete -c euwatch-describe-alarms -l action-prefix --description 'limit results to alarms whose actions\' ARNs beg… [See Man Page]'
complete -c euwatch-describe-alarms -l alarm-name-prefix --description 'limit results to alarms whose names begin with … [See Man Page]'
complete -c euwatch-describe-alarms -l show-long --description 'show all of the alarms\' info.'
complete -c euwatch-describe-alarms -l state-value --description 'limit results to alarms in a specific state.'
complete -c euwatch-describe-alarms -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euwatch-describe-alarms -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euwatch-describe-alarms -s U -l url --description 'instance monitoring service endpoint URL .'
complete -c euwatch-describe-alarms -l debug --description 'show debugging output.'
complete -c euwatch-describe-alarms -l debugger --description 'launch interactive debugger on error.'
complete -c euwatch-describe-alarms -l version --description 'show the program\'s version and exit.'
complete -c euwatch-describe-alarms -s I -l access-key-id --description '.'
complete -c euwatch-describe-alarms -s S -l secret-key --description '.'
complete -c euwatch-describe-alarms -s h -l help --description 'show this help message and exit.'

