# euwatch-get-stats
# Autogenerated from man page /usr/share/man/man1/euwatch-get-stats.1.gz
# using Deroffing man parser
complete -c euwatch-get-stats -s n -l namespace --description 'the metric\'s namespace (required).'
complete -c euwatch-get-stats -s s -l statistics --description 'the metric statistics to show (at least 1 required).'
complete -c euwatch-get-stats -l dimensions --description 'the dimensions of the metric to show.'
complete -c euwatch-get-stats -l start-time --description 'earliest time to retrieve data points for (defa… [See Man Page]'
complete -c euwatch-get-stats -l end-time --description 'latest time to retrieve data points for (default: now).'
complete -c euwatch-get-stats -l period --description 'granularity of the returned data points (must b… [See Man Page]'
complete -c euwatch-get-stats -l unit --description 'unit the metric is reported in.'
complete -c euwatch-get-stats -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euwatch-get-stats -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euwatch-get-stats -s U -l url --description 'instance monitoring service endpoint URL .'
complete -c euwatch-get-stats -l debug --description 'show debugging output.'
complete -c euwatch-get-stats -l debugger --description 'launch interactive debugger on error.'
complete -c euwatch-get-stats -l version --description 'show the program\'s version and exit.'
complete -c euwatch-get-stats -s I -l access-key-id --description '.'
complete -c euwatch-get-stats -s S -l secret-key --description '.'
complete -c euwatch-get-stats -s h -l help --description 'show this help message and exit.'

