# euwatch-enable-alarm-actions
# Autogenerated from man page /usr/share/man/man1/euwatch-enable-alarm-actions.1.gz
# using Deroffing man parser
complete -c euwatch-enable-alarm-actions -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euwatch-enable-alarm-actions -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euwatch-enable-alarm-actions -s U -l url --description 'instance monitoring service endpoint URL .'
complete -c euwatch-enable-alarm-actions -l debug --description 'show debugging output.'
complete -c euwatch-enable-alarm-actions -l debugger --description 'launch interactive debugger on error.'
complete -c euwatch-enable-alarm-actions -l version --description 'show the program\'s version and exit.'
complete -c euwatch-enable-alarm-actions -s I -l access-key-id --description '.'
complete -c euwatch-enable-alarm-actions -s S -l secret-key --description '.'
complete -c euwatch-enable-alarm-actions -s h -l help --description 'show this help message and exit.'

