# euwatch-describe-alarms-for-metric
# Autogenerated from man page /usr/share/man/man1/euwatch-describe-alarms-for-metric.1.gz
# using Deroffing man parser
complete -c euwatch-describe-alarms-for-metric -l metric-name --description 'name of the metric (required).'
complete -c euwatch-describe-alarms-for-metric -l namespace --description 'namespace of the metric (required).'
complete -c euwatch-describe-alarms-for-metric -l dimensions --description 'dimensions of the metric.'
complete -c euwatch-describe-alarms-for-metric -l period --description 'period over which statistics are applied.'
complete -c euwatch-describe-alarms-for-metric -l show-long --description 'show all of the alarms\' info.'
complete -c euwatch-describe-alarms-for-metric -l statistic --description 'statistic of the metric on which to trigger alarms.'
complete -c euwatch-describe-alarms-for-metric -l unit --description 'unit of measurement for statistics.'
complete -c euwatch-describe-alarms-for-metric -l show-empty-fields --description 'show empty values as "(nil)".'
complete -c euwatch-describe-alarms-for-metric -l region --description 'name of the region and/or user in config files … [See Man Page]'
complete -c euwatch-describe-alarms-for-metric -s U -l url --description 'instance monitoring service endpoint URL.'
complete -c euwatch-describe-alarms-for-metric -s I -l access-key-id --description '.'
complete -c euwatch-describe-alarms-for-metric -s S -l secret-key --description '.'
complete -c euwatch-describe-alarms-for-metric -l debug --description 'show debugging output.'
complete -c euwatch-describe-alarms-for-metric -l debugger --description 'launch interactive debugger on error.'
complete -c euwatch-describe-alarms-for-metric -l version --description 'show the program\'s version and exit.'
complete -c euwatch-describe-alarms-for-metric -s h -l help --description 'show this help message and exit.'

