# extcheck
# Autogenerated from man page /usr/share/man/man1/extcheck.1.gz
# using Deroffing man parser
complete -c extcheck -o verbose --description 'br Lists JAR files in the extension directory a… [See Man Page]'
complete -c extcheck -o Joption --description '.'

