# fail2ban-server
# Autogenerated from man page /usr/share/man/man1/fail2ban-server.1.gz
# using Deroffing man parser
complete -c fail2ban-server -s b --description 'start in background.'
complete -c fail2ban-server -s f --description 'start in foreground.'
complete -c fail2ban-server -s s --description 'socket path.'
complete -c fail2ban-server -s p --description 'pidfile path.'
complete -c fail2ban-server -s x --description 'force execution of the server (remove socket file).'
complete -c fail2ban-server -s h -l help --description 'display this help message.'
complete -c fail2ban-server -s V -l version --description 'print the version AUTHOR Written by Cyril Jaquier <cyril.'

