# fail2ban-client
# Autogenerated from man page /usr/share/man/man1/fail2ban-client.1.gz
# using Deroffing man parser
complete -c fail2ban-client -s c --description 'configuration directory.'
complete -c fail2ban-client -s s --description 'socket path.'
complete -c fail2ban-client -s p --description 'pidfile path.'
complete -c fail2ban-client -s d --description 'dump configuration.  For debugging.'
complete -c fail2ban-client -s i --description 'interactive mode.'
complete -c fail2ban-client -s v --description 'increase verbosity.'
complete -c fail2ban-client -s q --description 'decrease verbosity.'
complete -c fail2ban-client -s x --description 'force execution of the server (remove socket file).'
complete -c fail2ban-client -s h -l help --description 'display this help message.'
complete -c fail2ban-client -s V -l version --description 'print the version COMMAND BASIC.'

