# fail2ban-regex
# Autogenerated from man page /usr/share/man/man1/fail2ban-regex.1.gz
# using Deroffing man parser
complete -c fail2ban-regex -l version --description 'show program\'s version number and exit.'
complete -c fail2ban-regex -s h -l help --description 'show this help message and exit.'
complete -c fail2ban-regex -s l -l log-level --description 'Log level for the Fail2Ban logger to use.'
complete -c fail2ban-regex -s v -l verbose --description 'Be verbose in output.'
complete -c fail2ban-regex -s D -l debuggex --description 'Produce debuggex. com urls for debugging there.'
complete -c fail2ban-regex -l print-all-missed --description 'Either to print all missed lines.'
complete -c fail2ban-regex -l print-all-ignored --description 'Either to print all ignored lines.'
complete -c fail2ban-regex -s t -l log-traceback --description 'Enrich log-messages with compressed tracebacks.'
complete -c fail2ban-regex -l full-traceback --description 'Either to make the tracebacks full, not compres… [See Man Page]'

