# goaccess
# Autogenerated from man page /usr/share/man/man1/goaccess.1.gz
# using Deroffing man parser
complete -c goaccess -s f --description 'Path to input log file.'
complete -c goaccess -s c --description 'Prompt date and log format configuration window.'
complete -c goaccess -s e --description 'Exclude an IP from being counted under the HOST module.'
complete -c goaccess -s a --description 'Enable a list of User-Agents for the selected host.'
complete -c goaccess -s r --description 'Disables IP resolver CUSTOM LOG/DATE FORMAT GoA… [See Man Page]'

