# hh
# Autogenerated from man page /usr/share/man/man1/hh.1.gz
# using Deroffing man parser
complete -c hh -s h -l help --description 'Show help.'
complete -c hh -s n -l non-interactive --description 'Print filtered history on standard output and exit.'
complete -c hh -s f -l favorites --description 'Show favorites view immediately.'
complete -c hh -s s -l show-configuration --description 'Show configuration that can be added to ~/. bashrc.'
complete -c hh -s b -l show-blacklist --description 'Show blacklist of commands to be filtered out b… [See Man Page]'
complete -c hh -s V -l version --description 'Show version information KEYS.'

