# hstr
# Autogenerated from man page /usr/share/man/man1/hstr.1.gz
# using Deroffing man parser
complete -c hstr -s h -l help --description 'Show help.'
complete -c hstr -s n -l non-interactive --description 'Print filtered history on standard output and exit.'
complete -c hstr -s f -l favorites --description 'Show favorites view immediately.'
complete -c hstr -s s -l show-configuration --description 'Show configuration that can be added to ~/. bashrc.'
complete -c hstr -s b -l show-blacklist --description 'Show blacklist of commands to be filtered out b… [See Man Page]'
complete -c hstr -s V -l version --description 'Show version information KEYS.'

