# iostat
# Autogenerated from man page /usr/share/man/man1/iostat.1.gz
# using Deroffing man parser
complete -c iostat -s c --description 'Display the CPU utilization report.'
complete -c iostat -s d --description 'Display the device utilization report. if \'yes\'no\' \\{.'
complete -c iostat -l debuginfo --description 'Print debug output to stderr. \\}.'
complete -c iostat -s g --description 'Display statistics for a group of devices.'
complete -c iostat -s h --description 'Make the Device Utilization Report easier to read by a human.'
complete -c iostat -s j --description 'Display persistent device names.  Options  ID ,  LABEL , etc.'
complete -c iostat -s k --description 'Display statistics in kilobytes per second.'
complete -c iostat -s m --description 'Display statistics in megabytes per second.'
complete -c iostat -s N --description 'Display the registered device mapper names for … [See Man Page]'
complete -c iostat -s p --description 'The -p option displays statistics for block dev… [See Man Page]'
complete -c iostat -s T --description 'This option must be used with option -g and ind… [See Man Page]'
complete -c iostat -s t --description 'Print the time for each report displayed.'
complete -c iostat -s V --description 'Print version number then exit.'
complete -c iostat -s x --description 'Display extended statistics.'
complete -c iostat -s y --description 'Omit first report with statistics since system … [See Man Page]'
complete -c iostat -s z --description 'Tell iostat to omit output for any devices for … [See Man Page]'

