# jar
# Autogenerated from man page /usr/share/man/man1/jar.1.gz
# using Deroffing man parser
complete -c jar -s C --description 'br When creating (\\f3c) or updating (\\f3u) a JA… [See Man Page]'
complete -c jar -o Joption --description 'Sets the specified JVM option to be used when t… [See Man Page]'

