# javah
# Autogenerated from man page /usr/share/man/man1/javah.1.gz
# using Deroffing man parser
complete -c javah -s o --description 'br Concatenates the resulting header or source … [See Man Page]'
complete -c javah -s d --description 'br Sets the directory where the \\f3javah comman… [See Man Page]'
complete -c javah -o stubs --description 'br Causes the \\f3javah command to generate C de… [See Man Page]'
complete -c javah -o verbose --description 'br Indicates verbose output and causes the \\f3j… [See Man Page]'
complete -c javah -o help --description 'br Prints a help message for \\f3javah usage.'
complete -c javah -o version --description 'br Prints \\f3javah command release information.'
complete -c javah -o jni --description 'br Causes the \\f3javah command to create an out… [See Man Page]'
complete -c javah -o classpath --description 'br Specifies the path the \\f3javah command uses… [See Man Page]'
complete -c javah -o bootclasspath --description 'br Specifies the path from which to load bootstrap classes.'
complete -c javah -o old --description 'br Specifies that old JDK 1.'
complete -c javah -o force --description 'br Specifies that output files should always be written.'
complete -c javah -o Joption --description '.'

