# javaws
# Autogenerated from man page /usr/share/man/man1/javaws.1.gz
# using Deroffing man parser
complete -c javaws -o offline --description '.'
complete -c javaws -o Xnosplash --description '.'
complete -c javaws -o open --description '.'
complete -c javaws -o print --description '.'
complete -c javaws -o online --description '.'
complete -c javaws -o wait --description '.'
complete -c javaws -o verbose --description '.'
complete -c javaws -o Joption --description '.'
complete -c javaws -o system --description '.'
complete -c javaws -o viewer --description '.'
complete -c javaws -o clearcache --description '.'
complete -c javaws -o userConfig --description '.'
complete -c javaws -o uninstall --description '.'
complete -c javaws -o silent --description '.'
complete -c javaws -o codebase --description '.'
complete -c javaws -o shortcut --description '.'
complete -c javaws -o association --description '.'

