# jcmd
# Autogenerated from man page /usr/share/man/man1/jcmd.1.gz
# using Deroffing man parser
complete -c jcmd -s f --description 'Reads commands from the specified file.'
complete -c jcmd -o 'h
.br
-help' --description 'Prints a help message.'
complete -c jcmd -s l --description 'Prints the list of running Java processes ident… [See Man Page]'
complete -c jcmd -s h --description 'or.'
complete -c jcmd -o help --description 'option prints the tool\'s help message.  Note T{.'

