# jconsole
# Autogenerated from man page /usr/share/man/man1/jconsole.1.gz
# using Deroffing man parser
complete -c jconsole -o interval --description 'br Sets the update interval to n seconds (defau… [See Man Page]'
complete -c jconsole -o notile --description 'br Does not tile windows initially (for two or … [See Man Page]'
complete -c jconsole -o pluginpath --description 'br Specifies a list of directories or JAR files… [See Man Page]'
complete -c jconsole -o version --description 'br Displays release information and exits.'
complete -c jconsole -o help --description 'br Displays a help message.'
complete -c jconsole -o Jflag --description '.'

