# jdb
# Autogenerated from man page /usr/share/man/man1/jdb.1.gz
# using Deroffing man parser
complete -c jdb -o help --description 'br Displays a help message.'
complete -c jdb -o sourcepath --description 'br Uses the specified path to search for source… [See Man Page]'
complete -c jdb -o attach --description 'br Attaches the debugger to a running JVM with … [See Man Page]'
complete -c jdb -o listen --description 'br Waits for a running JVM to connect to the sp… [See Man Page]'
complete -c jdb -o launch --description 'br Starts the debugged application immediately … [See Man Page]'
complete -c jdb -o listconnectors --description 'br List the connectors available in this JVM.'
complete -c jdb -o connect --description 'br Connects to the target JVM with the named co… [See Man Page]'
complete -c jdb -o dbgtrace --description 'br Prints information for debugging the \\f3jdb command.'
complete -c jdb -o tclient --description 'br Runs the application in the Java HotSpot VM client.'
complete -c jdb -o tserver --description 'br Runs the application in the Java HotSpot VM server.'
complete -c jdb -o Joption --description '.'
complete -c jdb -s v -o 'verbose[:class' --description '.'
complete -c jdb -o Dname --description '.'
complete -c jdb -o classpath --description '.'
complete -c jdb -o Xoption --description '.'

