# jhat
# Autogenerated from man page /usr/share/man/man1/jhat.1.gz
# using Deroffing man parser
complete -c jhat -o stack --description 'br Turns off tracking object allocation call stack.'
complete -c jhat -o refs --description 'br Turns off tracking of references to objects.'
complete -c jhat -o port --description 'br Sets the port for the \\f3jhat HTTP server.  Default is 7000.'
complete -c jhat -o exclude --description 'br Specifies a file that lists data members tha… [See Man Page]'
complete -c jhat -o baseline --description 'br Specifies a baseline heap dump.'
complete -c jhat -o debug --description 'br Sets the debug level for this tool.'
complete -c jhat -o version --description 'br Reports the release number and exits.'
complete -c jhat -s h --description 'br Dsiplays a help message and exits.'
complete -c jhat -o help --description 'br Displays a help message and exits.'
complete -c jhat -o Jflag --description '.'

