# jjs
# Autogenerated from man page /usr/share/man/man1/jjs.1.gz
# using Deroffing man parser
complete -c jjs -o cp --description 'Specifies the path to the supporting class file… [See Man Page]'
complete -c jjs -o Dname --description 'Sets a system property to be passed to the scri… [See Man Page]'
complete -c jjs -o 'doe
.br
--dump-on-error' --description 'Provides a full stack trace when an error occurs.'
complete -c jjs -o 'fv
.br
--fullversion' --description 'Prints the full Nashorn version string.'
complete -c jjs -o fx --description 'Launches the script as a JavaFX application.'
complete -c jjs -o 'h
.br
-help' --description 'Prints the list of options and their descriptions.'
complete -c jjs -l language --description 'Specifies the ECMAScript language version.'
complete -c jjs -o 'ot
.br
--optimistic-types' --description 'Enables or disables optimistic type assumptions… [See Man Page]'
complete -c jjs -o scripting --description 'Enables shell scripting features.'
complete -c jjs -o strict --description 'Enables strict mode, which enforces stronger ad… [See Man Page]'
complete -c jjs -s t --description 'Sets the specified time zone for script execution.'
complete -c jjs -o 'v
.br
-version' --description 'Prints the Nashorn version string.'
complete -c jjs -o classpath --description '.'
complete -c jjs -o doe --description '.'
complete -c jjs -l dump-on-error --description '.'
complete -c jjs -o fv --description '.'
complete -c jjs -l fullversion --description '.'
complete -c jjs -s h --description '.'
complete -c jjs -o help --description '.'
complete -c jjs -o ot --description '.'
complete -c jjs -l optimistic-types --description '.'
complete -c jjs -o timezone --description '.'
complete -c jjs -s v --description '.'
complete -c jjs -o version --description '.'

