# jmc
# Autogenerated from man page /usr/share/man/man1/jmc.1.gz
# using Deroffing man parser
complete -c jmc -o help --description 'Prints jmc command help.'
complete -c jmc -o version --description 'Prints the version of Java Mission Control and exit.'
complete -c jmc -o showversion --description 'Prints the version of Java Mission Control and continue.'
complete -c jmc -o debug --description 'Enables debug output.'
complete -c jmc -o consoleLog --description 'Prints the Eclipse log on the console.  (Flag from Eclipse).'
complete -c jmc -o data --description 'Sets the workspace used while running Java Mission Control.'
complete -c jmc -o open --description 'Opens the file in Java Mission Control.'
complete -c jmc -o vmargs --description 'Overrides the JVM arguments specified in the jmc.'
complete -c jmc -l 'launcher.appendVmargs' --description 'Appends JVM arguments from the -vmargs flag to … [See Man Page]'
complete -c jmc -o nosplash --description '.'

