# jps
# Autogenerated from man page /usr/share/man/man1/jps.1.gz
# using Deroffing man parser
complete -c jps -s q --description 'br Suppresses the output of the class name, JAR… [See Man Page]'
complete -c jps -s m --description 'br Displays the arguments passed to the \\f3main method.'
complete -c jps -s l --description 'br Displays the full package name for the appli… [See Man Page]'
complete -c jps -s v --description 'br Displays the arguments passed to the JVM.'
complete -c jps -s V --description 'br Suppresses the output of the class name, JAR… [See Man Page]'
complete -c jps -o Joption --description '.'

