# jstack
# Autogenerated from man page /usr/share/man/man1/jstack.1.gz
# using Deroffing man parser
complete -c jstack -s F --description 'br Force a stack dump when \\f3jstack [\\f3-l] \\f… [See Man Page]'
complete -c jstack -s l --description 'br Long listing.'
complete -c jstack -s m --description 'br Prints a mixed mode stack trace that has bot… [See Man Page]'
complete -c jstack -s h --description 'br Prints a help message.'
complete -c jstack -o help --description '.'

