# jstatd
# Autogenerated from man page /usr/share/man/man1/jstatd.1.gz
# using Deroffing man parser
complete -c jstatd -o nr --description 'br Does not attempt to create an internal RMI r… [See Man Page]'
complete -c jstatd -s p --description 'br The port number where the RMI registry is ex… [See Man Page]'
complete -c jstatd -s n --description 'br Name to which the remote RMI object is bound… [See Man Page]'
complete -c jstatd -o Joption --description '.'

