# ksplice-uptrack
# Autogenerated from man page /usr/share/man/man8/ksplice-uptrack.8.gz
# using Type1
complete -c ksplice-uptrack -s v -l verbose --description 'Provide more detail about what the program is doing.'
complete -c ksplice-uptrack -s q -l quiet --description 'Do not print status messages.'
complete -c ksplice-uptrack -s y --description 'Assume \\*(L"yes\\*(R" to all user prompts.'
complete -c ksplice-uptrack -s n --description 'Assume \\*(L"no\\*(R" to all user prompts.'
complete -c ksplice-uptrack -l all --description 'Take action for all of the IDs that Uptrack kno… [See Man Page]'
complete -c ksplice-uptrack -l available --description 'With \\f(CW\\*(C`uptrack-show\\*(C\', instead of sh… [See Man Page]'
complete -c ksplice-uptrack -l count --description 'With \\f(CW\\*(C`uptrack-show\\*(C\', instead of sh… [See Man Page]'
complete -c ksplice-uptrack -l wait --description 'When installing or removing a sequence of updat… [See Man Page]'

