# logwatch
# Autogenerated from man page /usr/share/man/man8/logwatch.8.gz
# using Deroffing man parser
complete -c logwatch -l detail --description 'This is the detail level of the report.'
complete -c logwatch -l logfile --description 'This will force Logwatch to process only the se… [See Man Page]'
complete -c logwatch -l service --description 'This will force Logwatch to process only the se… [See Man Page]'
complete -c logwatch -l mailto --description 'Mail the results to the email address or user s… [See Man Page]'
complete -c logwatch -l range --description 'You can specify a date-range to process.'
complete -c logwatch -l archives --description 'Each log-file-group has basic logfiles (i. e.'
complete -c logwatch -l debug --description 'For debugging purposes.   level can range from 0 to 100.'
complete -c logwatch -l filename --description 'Save the output to  file-name instead of displa… [See Man Page]'
complete -c logwatch -l logdir --description 'Look in  directory for log subdirectories or lo… [See Man Page]'
complete -c logwatch -l hostlimit --description 'Limit report to hostname - host1, host2.'
complete -c logwatch -l hostname --description 'Use  hostname for the reports instead of this s… [See Man Page]'
complete -c logwatch -l html_wrap --description 'Number of characters that html output should be wrapped to.'
complete -c logwatch -l numeric --description 'Inhibits additional name lookups, displaying IP… [See Man Page]'
complete -c logwatch -l usage --description 'Displays usage information.'
complete -c logwatch -l help --description 'same as --usage.  FILES /usr/share/logwatch/.'

