# lsdistcc
# Autogenerated from man page /usr/share/man/man1/lsdistcc.1.gz
# using Type1
complete -c lsdistcc -l help --description 'Displays summary instructions.'
complete -c lsdistcc -s l --description 'Output latency in milliseconds after each hostn… [See Man Page]'
complete -c lsdistcc -s n --description 'Print IP address rather than name.'
complete -c lsdistcc -s x --description 'Append ,down to down hosts in host list.'
complete -c lsdistcc -s t --description 'Set number of seconds to stop searching after [7].'
complete -c lsdistcc -s h --description 'Set number of milliseconds before retrying gethostbyname [500].'
complete -c lsdistcc -s c --description 'Set number of milliseconds before giving up on … [See Man Page]'
complete -c lsdistcc -s k --description 'Set number of milliseconds before giving up on … [See Man Page]'
complete -c lsdistcc -s m --description 'Set number of bits of address that must match f… [See Man Page]'
complete -c lsdistcc -s o --description 'Set number of extra DNS requests to send [1].'
complete -c lsdistcc -s g --description 'Set number of missing DNS entries to tolerate [0].'
complete -c lsdistcc -s r --description 'Port to connect to [3632].'
complete -c lsdistcc -s P --description 'Protocol version to use (1-3) [1].'
complete -c lsdistcc -s p --description 'Name of compiler to use [none].'
complete -c lsdistcc -s d --description 'Append DNS domain name to format.'

