# mimeview
# Autogenerated from man page /usr/share/man/man1/mimeview.1.gz
# using Deroffing man parser
complete -c mimeview -s a -l 'no-ask[' --description 'do not ask for confirmation before displaying f… [See Man Page]'
complete -c mimeview -s d -l 'debug[' --description 'enable debugging output.'
complete -c mimeview -s h -l no-interactive -l print --description 'disable interactive mode.'
complete -c mimeview -l 'metamail[' --description 'use metamail to display files.'
complete -c mimeview -s n -l dry-run --description 'do not do anything, just print what whould be done.'
complete -c mimeview -s t -l mimetypes --description 'use this mime. types file P Common options.'
complete -c mimeview -l config-file -l rcfile --description 'load this configuration file.'
complete -c mimeview -l config-help --description 'show configuration file summary.'
complete -c mimeview -l config-lint -l rcfile-lint --description 'check configuration file syntax and exit.'
complete -c mimeview -l config-verbose -l rcfile-verbose --description 'verbosely log parsing of the configuration files.'
complete -c mimeview -l no-site-config -l no-site-rcfile --description 'do not load site configuration file.'
complete -c mimeview -l no-user-config -l no-user-rcfile --description 'do not load user configuration file.'
complete -c mimeview -l set --description 'set configuration parameter.'
complete -c mimeview -l show-config-options --description 'show compilation options P Global debugging settings.'
complete -c mimeview -l debug-level --description 'set Mailutils debugging level.'
complete -c mimeview -l debug-line-info --description 'show source info with debugging messages.'
complete -c mimeview -s '?' -l help --description 'give this help list.'
complete -c mimeview -l usage --description 'give a short usage message.'
complete -c mimeview -s V -l version --description 'print program version.'

