# mpstat
# Autogenerated from man page /usr/share/man/man1/mpstat.1.gz
# using Deroffing man parser
complete -c mpstat -s A --description 'This option is equivalent to specifying  "-u -I ALL -P ALL".'
complete -c mpstat -s I --description 'Report interrupts statistics.'
complete -c mpstat -s P --description 'Indicate the processor number for which statist… [See Man Page]'
complete -c mpstat -s u --description 'Report CPU utilization.'
complete -c mpstat -s V --description 'Print version number then exit.'

