# mu-tool
# Autogenerated from man page /usr/share/man/man1/mu-tool.1.gz
# using Deroffing man parser
complete -c mu-tool -l config-file -l rcfile --description 'load this configuration file.'
complete -c mu-tool -l config-help --description 'show configuration file summary.'
complete -c mu-tool -l config-lint -l rcfile-lint --description 'check configuration file syntax and exit.'
complete -c mu-tool -l config-verbose -l rcfile-verbose --description 'verbosely log parsing of the configuration files.'
complete -c mu-tool -l no-site-config -l no-site-rcfile --description 'do not load site configuration file.'
complete -c mu-tool -l no-user-config -l no-user-rcfile --description 'do not load user configuration file.'
complete -c mu-tool -l set --description 'set configuration parameter.'
complete -c mu-tool -l show-config-options --description 'show compilation options P Global debugging settings.'
complete -c mu-tool -l debug-level --description 'set Mailutils debugging level.'
complete -c mu-tool -l debug-line-info --description 'show source info with debugging messages.'
complete -c mu-tool -s '?' -l help --description 'give this help list.'
complete -c mu-tool -l usage --description 'give a short usage message.'
complete -c mu-tool -s V -l version --description 'print program version REPORTING BUGS Report bug… [See Man Page]'

