# native2ascii
# Autogenerated from man page /usr/share/man/man1/native2ascii.1.gz
# using Deroffing man parser
complete -c native2ascii -o reverse --description 'br Perform the reverse operation: Converts a fi… [See Man Page]'
complete -c native2ascii -o encoding --description 'br Specifies the name of the character encoding… [See Man Page]'
complete -c native2ascii -o Joption --description '.'

