# ncdu
# Autogenerated from man page /usr/share/man/man1/ncdu.1.gz
# using Type1
complete -c ncdu -s h --description 'Print a short help message and quit.'
complete -c ncdu -s v --description 'Print ncdu version and quit.'
complete -c ncdu -s f --description 'Load the given file, which has earlier been cre… [See Man Page]'
complete -c ncdu -s o --description 'Export all necessary information to \\s-1FILE\\s0… [See Man Page]'
complete -c ncdu -s 0 --description 'Don\'t give any feedback while scanning a direct… [See Man Page]'
complete -c ncdu -s 1 --description 'Similar to \\f(CW\\*(C`-0\\*(C\', but does give fee… [See Man Page]'
complete -c ncdu -s 2 --description 'Provide a full-screen ncurses interface while s… [See Man Page]'
complete -c ncdu -s q --description 'Quiet mode.'
complete -c ncdu -s r --description 'Read-only mode.'
complete -c ncdu -s x --description 'Do not cross filesystem boundaries, i. e.'
complete -c ncdu -l exclude --description 'Exclude files that match \\s-1PATTERN\\s0.'
complete -c ncdu -s X -l exclude-from --description 'Exclude files that match any pattern in \\s-1FILE\\s0.'

