# nfsiostat
# Autogenerated from man page /usr/share/man/man1/nfsiostat.1.gz
# using Deroffing man parser
complete -c nfsiostat -l debuginfo --description 'Print debug output to stderr. \\}.'
complete -c nfsiostat -s h --description 'Make the NFS report easier to read by a human.'
complete -c nfsiostat -s k --description 'Display statistics in kilobytes per second.'
complete -c nfsiostat -s m --description 'Display statistics in megabytes per second.'
complete -c nfsiostat -s t --description 'Print the time for each report displayed.'
complete -c nfsiostat -s V --description 'Print version number then exit.'

