# nload
# Autogenerated from man page /usr/share/man/man1/nload.1.gz
# using Deroffing man parser
complete -c nload -s a --description 'Sets the length in seconds of the time window f… [See Man Page]'
complete -c nload -s i --description 'Specifies the 100% mark in kBit/s of the graph … [See Man Page]'
complete -c nload -s m --description 'Show multiple devices at a time; do not show th… [See Man Page]'
complete -c nload -s o --description 'Same as -i but for the graph indicating the out… [See Man Page]'
complete -c nload -s t --description 'Determines the refresh interval of the display in milliseconds.'
complete -c nload -s u --description 'Sets the type of unit used for the display of traffic numbers.'
complete -c nload -s U --description 'Same as -u, but for an amount of data, e. g.'
complete -c nload -s h -l help --description 'Show a short summary of these command line options.'

