# orbd
# Autogenerated from man page /usr/share/man/man1/orbd.1.gz
# using Deroffing man parser
complete -c orbd -o ORBInitialPort --description 'br Required.'
complete -c orbd -o port --description 'br Specifies the activation port where ORBD sho… [See Man Page]'
complete -c orbd -o defaultdb --description 'br Specifies the base where the ORBD persistent… [See Man Page]'
complete -c orbd -o serverPollingTime --description 'br Specifies how often ORBD checks for the heal… [See Man Page]'
complete -c orbd -o serverStartupDelay --description 'br Specifies how long ORBD waits before sending… [See Man Page]'
complete -c orbd -o Joption --description '.'

