# pidstat
# Autogenerated from man page /usr/share/man/man1/pidstat.1.gz
# using Deroffing man parser
complete -c pidstat -s C --description 'Display only tasks whose command name includes … [See Man Page]'
complete -c pidstat -s d --description 'Report I/O statistics (kernels 2. 6. 20 and later only).'
complete -c pidstat -s h --description 'Display all activities horizontally on a single line.'
complete -c pidstat -s I --description 'In an SMP environment, indicate that tasks CPU … [See Man Page]'
complete -c pidstat -s l --description 'Display the process command name and all its arguments.'
complete -c pidstat -s p --description 'Select tasks (processes) for which statistics a… [See Man Page]'
complete -c pidstat -s r --description 'Report page faults and memory utilization.'
complete -c pidstat -s s --description 'Report stack utilization.'
complete -c pidstat -s T --description 'This option specifies what has to be monitored … [See Man Page]'
complete -c pidstat -s t --description 'Also display statistics for threads associated … [See Man Page]'
complete -c pidstat -s U --description 'Display the real user name of the tasks being m… [See Man Page]'
complete -c pidstat -s u --description 'Report CPU utilization.'
complete -c pidstat -s V --description 'Print version number then exit.'
complete -c pidstat -s v --description 'Report values of some kernel tables.'
complete -c pidstat -s w --description 'Report task switching activity (kernels 2. 6.'

