# pollinate
# Autogenerated from man page /usr/share/man/man1/pollinate.1.gz
# using Deroffing man parser
complete -c pollinate -s b -l binary --description 'rather than producing hex text sha512sum(1) out… [See Man Page]'
complete -c pollinate -s c -l curl-opts --description 'options to pass through to curl(1).'
complete -c pollinate -s d -l device --description 'device to seed (default is /dev/urandom); note,… [See Man Page]'
complete -c pollinate -s n -l no-challenge --description 'disable the challenge/response portion of the p… [See Man Page]'
complete -c pollinate -s i -l insecure --description 'ignore SSL/TLS certificate errors (use of this … [See Man Page]'
complete -c pollinate -s p -l pool --description 'remote pollen(8) server pool to interact with; … [See Man Page]'
complete -c pollinate -s r -l reseed --description 'by default, pollinate technically only needs to… [See Man Page]'
complete -c pollinate -s s -l server --description 'remote pollen(8) server to interact with; if th… [See Man Page]'
complete -c pollinate -s t -l testing --description 'test communications with the pollen(8) server; … [See Man Page]'
complete -c pollinate -s q -l quiet --description 'silence any log messages.'
complete -c pollinate -s w -l wait --description 'time in seconds you\'re willing to wait for a re… [See Man Page]'

