# posttls-finger
# Autogenerated from man page /usr/share/man/man1/posttls-finger.1.gz
# using Deroffing man parser
complete -c posttls-finger -s h -s o -s S -s t -s T -s v --description 'are available.'
complete -c posttls-finger -s r --description 'for the new server, and the reconnect is repeat… [See Man Page]'
complete -c posttls-finger -s a --description 'Address family preference: ipv4, ipv6 or any.'
complete -c posttls-finger -s A --description 'A list of PEM trust-anchor files that overrides… [See Man Page]'
complete -c posttls-finger -s c --description 'Disable SMTP chat logging; only TLS-related inf… [See Man Page]'
complete -c posttls-finger -s C --description 'Print the remote SMTP server certificate trust … [See Man Page]'
complete -c posttls-finger -s P --description 'missing issuer certificates.'
complete -c posttls-finger -s d --description 'The message digest algorithm to use for reporti… [See Man Page]'
complete -c posttls-finger -s f --description 'Lookup the associated DANE TLSA RRset even when… [See Man Page]'
complete -c posttls-finger -s F --description 'The PEM formatted CAfile for remote SMTP server… [See Man Page]'
complete -c posttls-finger -s g --description 'The minimum TLS cipher grade used by posttls-finger.'
complete -c posttls-finger -s l --description 'The security level for the connection, default … [See Man Page]'
complete -c posttls-finger -s L --description 'Fine-grained TLS logging options.'
complete -c posttls-finger -s m --description 'When the -r delay option is specified, the -m o… [See Man Page]'
complete -c posttls-finger -s p --description 'List of TLS protocols that posttls-finger will … [See Man Page]'

