# qmqp-sink
# Autogenerated from man page /usr/share/man/man1/qmqp-sink.1.gz
# using Deroffing man parser
complete -c qmqp-sink -s 4 --description 'Support IPv4 only.'
complete -c qmqp-sink -s 6 --description 'Support IPv6 only.'
complete -c qmqp-sink -s c --description 'Display a running counter that is updated whene… [See Man Page]'
complete -c qmqp-sink -s v --description 'Increase verbosity.'
complete -c qmqp-sink -s x --description 'Terminate after time seconds.'

