# qshape
# Autogenerated from man page /usr/share/man/man1/qshape.1.gz
# using Deroffing man parser
complete -c qshape -s s --description 'Display the sender domain distribution instead … [See Man Page]'
complete -c qshape -s p --description 'Generate aggregate statistics for parent domains.'
complete -c qshape -s m --description 'When used with the -p option, sets the minimum … [See Man Page]'
complete -c qshape -s b --description 'The age distribution is broken up into a sequen… [See Man Page]'
complete -c qshape -s t --description 'The age limit in minutes for the first time bucket.'
complete -c qshape -s l --description 'Instead of using a geometric age sequence, use … [See Man Page]'
complete -c qshape -s w --description 'The output is right justified, with the counts … [See Man Page]'
complete -c qshape -s N --description 'When the output device is a terminal, intermedi… [See Man Page]'
complete -c qshape -s n --description 'When reporting intermediate or final results to… [See Man Page]'
complete -c qshape -s c --description 'The main.'

