# resize-part-image
# Autogenerated from man page /usr/share/man/man1/resize-part-image.1.gz
# using Deroffing man parser
complete -c resize-part-image -s v -l verbose --description 'show output of resize and fsck commands.'

