# rmic
# Autogenerated from man page /usr/share/man/man1/rmic.1.gz
# using Deroffing man parser
complete -c rmic -o bootclasspath --description 'br Overrides the location of bootstrap class files.'
complete -c rmic -o classpath --description 'br Specifies the path the \\f3rmic command uses … [See Man Page]'
complete -c rmic -s d --description 'br Specifies the root destination directory for… [See Man Page]'
complete -c rmic -o extdirs --description 'br Overrides the location of installed extensions.'
complete -c rmic -s g --description 'br Enables the generation of all debugging info… [See Man Page]'
complete -c rmic -o idl --description 'br Causes the \\f3rmic command to generate OMG I… [See Man Page]'
complete -c rmic -o iiop --description 'br Causes the \\f3rmic command to generate IIOP … [See Man Page]'
complete -c rmic -s J --description 'br Used with any Java command, the \\f3-J option… [See Man Page]'
complete -c rmic -o keep -o keepgenerated --description 'br Retains the generated \\f3.'
complete -c rmic -o nowarn --description 'br Turns off warnings.  When the \\f3-nowarn options is used.'
complete -c rmic -o nowrite --description 'br Does not write compiled classes to the file system.'
complete -c rmic -o vcompat --description 'br Generates stub and skeleton classes that are… [See Man Page]'
complete -c rmic -o verbose --description 'br Causes the compiler and linker to print out … [See Man Page]'
complete -c rmic -o 'v1.1' --description 'br Generates stub and skeleton classes for the 1.'
complete -c rmic -o 'idlFilefromJavaPackage[.class]' -o idlFile --description '.'
complete -c rmic -o 'v1.2' --description '.'

