# rmid
# Autogenerated from man page /usr/share/man/man1/rmid.1.gz
# using Deroffing man parser
complete -c rmid -o Coption --description 'br Specifies an option that is passed as a comm… [See Man Page]'
complete -c rmid -o Joption --description 'br Specifies an option that is passed to the Ja… [See Man Page]'
complete -c rmid -o 'J-Dsun.rmi.activation.execPolicy' --description 'br Specifies the policy that RMID employs to ch… [See Man Page]'
complete -c rmid -o log --description 'br Specifies the name of the directory the acti… [See Man Page]'
complete -c rmid -o port --description 'br Specifies the port the registry uses.'
complete -c rmid -o stop --description '.'

