# s3fs
# Autogenerated from man page /usr/share/man/man1/s3fs.1
# using Deroffing man parser
complete -c s3fs -s h -l help --description 'print help.'
complete -c s3fs -l version --description 'print version.'
complete -c s3fs -s f --description 'FUSE foreground option - do not run as daemon.'
complete -c s3fs -s s --description 'FUSE singlethreaded option (disables multi-thre… [See Man Page]'
complete -c s3fs -s o --description 'the default canned acl to apply to all written S3 objects, e.'

