# sadc
# Autogenerated from man page /usr/share/man/man8/sadc.8.gz
# using Deroffing man parser
complete -c sadc -s C --description 'When neither the  interval nor the  count param… [See Man Page]'
complete -c sadc -s F --description 'The creation of  outfile will be forced.'
complete -c sadc -s L --description 'sadc will try to get an exclusive lock on the  … [See Man Page]'
complete -c sadc -s S --description 'Specify which optional activities should be col… [See Man Page]'
complete -c sadc -s V --description 'Print version number then exit.'

