# sadf
# Autogenerated from man page /usr/share/man/man1/sadf.1.gz
# using Deroffing man parser
complete -c sadf -s C --description 'Tell  sadf to display comments present in file.'
complete -c sadf -s d --description 'Print the contents of the data file in a format… [See Man Page]'
complete -c sadf -s e --description 'Set the ending time of the report, given in local time.'
complete -c sadf -s H --description 'Display only the header of the report (when applicable).'
complete -c sadf -s h --description 'When used in conjunction with option -d, all ac… [See Man Page]'
complete -c sadf -s j --description 'Print the contents of the data file in JSON (Ja… [See Man Page]'
complete -c sadf -s P --description 'Tell  sadf that processor dependent statistics … [See Man Page]'
complete -c sadf -s p --description 'Print the contents of the data file in a format… [See Man Page]'
complete -c sadf -s s --description 'Set the starting time of the data (given in loc… [See Man Page]'
complete -c sadf -s T --description 'Display timestamp in local time instead of UTC … [See Man Page]'
complete -c sadf -s t --description 'Display timestamp in the original local time of… [See Man Page]'
complete -c sadf -s U --description 'Display timestamp (UTC - Coordinated Universal … [See Man Page]'
complete -c sadf -s V --description 'Print version number then exit.'
complete -c sadf -s x --description 'Print the contents of the data file in XML format.'

