# serialver
# Autogenerated from man page /usr/share/man/man1/serialver.1.gz
# using Deroffing man parser
complete -c serialver -o classpath --description 'br Sets the search path for application classes and resources.'
complete -c serialver -o show --description 'br Displays a simple user interface.'
complete -c serialver -o Joption --description '.'
complete -c serialver -o 'J-Djava.security.manager' --description 'When necessary, a security policy can be specif… [See Man Page]'
complete -c serialver -o 'J-Djava.security.policy' --description 'SEE ALSO    .'

