# stress
# Autogenerated from man page /usr/share/man/man1/stress.1.gz
# using Deroffing man parser
complete -c stress -s '?' -l help --description 'show this help statement.'
complete -c stress -l version --description 'show version statement.'
complete -c stress -s v -l verbose --description 'be verbose.'
complete -c stress -s q -l quiet --description 'be quiet.'
complete -c stress -s n -l dry-run --description 'show what would have been done.'
complete -c stress -s t -l timeout --description 'timeout after N seconds.'
complete -c stress -l backoff --description 'wait factor of N microseconds before work starts.'
complete -c stress -s c -l cpu --description 'spawn N workers spinning on sqrt().'
complete -c stress -s i -l io --description 'spawn N workers spinning on sync().'
complete -c stress -s m -l vm --description 'spawn N workers spinning on malloc()/free().'
complete -c stress -l vm-bytes --description 'malloc B bytes per vm worker (default is 256MB).'
complete -c stress -l vm-stride --description 'touch a byte every B bytes (default is 4096).'
complete -c stress -l vm-hang --description 'sleep N secs before free (default is none, 0 is inf).'
complete -c stress -l vm-keep --description 'redirty memory instead of freeing and reallocating.'
complete -c stress -s d -l hdd --description 'spawn N workers spinning on write()/unlink().'
complete -c stress -l hdd-bytes --description 'write B bytes per hdd worker (default is 1GB).'
complete -c stress -l hdd-noclean --description 'do not unlink files created by hdd workers.'

