# uprecords
# Autogenerated from man page /usr/share/man/man1/uprecords.1.gz
# using Deroffing man parser
complete -c uprecords -s '?' --description 'Show usage.'
complete -c uprecords -s a --description 'Do not print ANSI codes.'
complete -c uprecords -s b -s B --description 'Sort by time of bootup, oldest entry first.  -B reverses.'
complete -c uprecords -s c --description 'Do not show current entry if not in top entries.'
complete -c uprecords -s f --description 'Run continuously in a loop.'
complete -c uprecords -s k -s K --description 'Sort by kernel/system name.  -K reverses.  Option implies -s.'
complete -c uprecords -s M --description 'Show next milestone.'
complete -c uprecords -s s --description 'Do not print extra statistics.'
complete -c uprecords -s i --description 'Use <interval> seconds for loop instead of 5, implies -f.'
complete -c uprecords -s m --description 'Show a maximum of top COUNT entries instead of 10.'
complete -c uprecords -s v --description 'Show version information.'

