# uptimed
# Autogenerated from man page /usr/share/man/man8/uptimed.8.gz
# using Deroffing man parser
complete -c uptimed -s '?' --description 'Show usage.'
complete -c uptimed -s b --description 'Create bootid and exit.'
complete -c uptimed -s p --description 'Write PID to pidfile <file>.'
complete -c uptimed -s e --description 'Send mail to <email> at milestones/records.'
complete -c uptimed -s i --description 'Use <interval> seconds for loop.'
complete -c uptimed -s m --description 'Log a maximum of <count> entries.'
complete -c uptimed -s t --description 'Set the minimum uptime to be considered a record.'
complete -c uptimed -s v --description 'Show version information.'

