# uptrack-uname
# Autogenerated from man page /usr/share/man/man8/uptrack-uname.8.gz
# using Type1
complete -c uptrack-uname -l version --description 'Show program\'s version number and exit.'
complete -c uptrack-uname -l help --description 'Show a help message and exit.'
complete -c uptrack-uname -s a -l all --description 'Print all information, in the following order, … [See Man Page]'
complete -c uptrack-uname -s s -l kernel-name --description 'Print the kernel name.'
complete -c uptrack-uname -s n -l nodename --description 'Print the network node hostname.'
complete -c uptrack-uname -s r -l kernel-release --description 'Print the kernel release.'
complete -c uptrack-uname -s v -l kernel-version --description 'Print the kernel version.'
complete -c uptrack-uname -s m -l machine --description 'Print the machine hardware name.'
complete -c uptrack-uname -s p -l processor --description 'Print the processor type or \\*(L"unknown\\*(R".'
complete -c uptrack-uname -s i -l hardware-platform --description 'Print the hardware platform or \\*(L"unknown\\*(R".'
complete -c uptrack-uname -s o -l operating-system --description 'Print the operating system.'
complete -c uptrack-uname -l package-version --description 'Print the effective version of the distribution… [See Man Page]'

