# uptrack-install
# Autogenerated from man page /usr/share/man/man8/uptrack-install.8.gz
# using Type1
complete -c uptrack-install -s v -l verbose --description 'Provide more detail about what the program is doing.'
complete -c uptrack-install -s q -l quiet --description 'Do not print status messages.'
complete -c uptrack-install -s y --description 'Assume \\*(L"yes\\*(R" to all user prompts.'
complete -c uptrack-install -s n --description 'Assume \\*(L"no\\*(R" to all user prompts.'
complete -c uptrack-install -l all --description 'Take action for all of the IDs that Uptrack kno… [See Man Page]'
complete -c uptrack-install -l available --description 'With \\f(CW\\*(C`uptrack-show\\*(C\', instead of sh… [See Man Page]'
complete -c uptrack-install -l count --description 'With \\f(CW\\*(C`uptrack-show\\*(C\', instead of sh… [See Man Page]'
complete -c uptrack-install -l wait --description 'When installing or removing a sequence of updat… [See Man Page]'

