# vnstatd
# Autogenerated from man page /usr/share/man/man1/vnstatd.1.gz
# using Deroffing man parser
complete -c vnstatd -l config --description 'Use  file as config file instead of using norma… [See Man Page]'
complete -c vnstatd -s d -l daemon --description 'Fork process to background and run as a daemon.'
complete -c vnstatd -s D -l debug --description 'Provide additional output for debug purposes.'
complete -c vnstatd -l noadd --description 'Disable automatic creation of new databases for… [See Man Page]'
complete -c vnstatd -s n -l nodaemon --description 'Stay in foreground attached to the current term… [See Man Page]'
complete -c vnstatd -s p -l pidfile --description 'Write the process id to  file and use it for lo… [See Man Page]'
complete -c vnstatd -s s -l sync --description 'Synchronize internal counters in the database w… [See Man Page]'
complete -c vnstatd -s v -l version --description 'Show current version.'
complete -c vnstatd -s '?' -l help --description 'Show a command summary.'

