# write-mime-multipart
# Autogenerated from man page /usr/share/man/man1/write-mime-multipart.1.gz
# using Deroffing man parser
complete -c write-mime-multipart -s h -l help --description 'Show usage message.'
complete -c write-mime-multipart -s o -l output --description 'write output to FILE [default is stdout].'
complete -c write-mime-multipart -s z -l gzip --description 'compress output with gzip.'
complete -c write-mime-multipart -s d -l default --description 'if not provided assume mime-type of DEFTYPE [de… [See Man Page]'
complete -c write-mime-multipart -l delim --description 'use delimiter DELIM [default is \':\'].'

