# wsgen
# Autogenerated from man page /usr/share/man/man1/wsgen.1.gz
# using Deroffing man parser
complete -c wsgen -o classpath --description 'br The location of the input class files.'
complete -c wsgen -o cp --description 'br The location of the input class files.'
complete -c wsgen -s d --description 'br The location for where to place generated output files.'
complete -c wsgen -o extension --description 'br Allow vendor extensions.'
complete -c wsgen -o help --description 'br Displays a help message about the \\f3wsgen command.'
complete -c wsgen -o keep --description 'br Keeps the generated files.'
complete -c wsgen -s r --description 'br Uses this option with the \\f3-wsdl option to… [See Man Page]'
complete -c wsgen -s s --description 'br The location for where to place generated source files.'
complete -c wsgen -o verbose --description 'br Displays compiler messages.'
complete -c wsgen -o version --description 'br Prints release information.'
complete -c wsgen -o wsdl --description 'br An optional command that generates a WSDL fi… [See Man Page]'
complete -c wsgen -o servicename --description 'br Used only with the \\f3-wsdl option to specif… [See Man Page]'
complete -c wsgen -o portname --description '.'

